// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.9
// 	protoc        (unknown)
// source: non_standart_names.proto

package testpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	_ "google.golang.org/protobuf/types/known/fieldmaskpb"
	structpb "google.golang.org/protobuf/types/known/structpb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// NonStandardMessage has oddly named fields.
type NonStandardMessage struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Id represents the message identifier.
	Id            string                    `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Num           int64                     `protobuf:"varint,2,opt,name=Num,proto3" json:"Num,omitempty"`
	LineNum       int64                     `protobuf:"varint,3,opt,name=line_num,json=lineNum,proto3" json:"line_num,omitempty"`
	LangIdent     string                    `protobuf:"bytes,4,opt,name=langIdent,proto3" json:"langIdent,omitempty"`
	STATUS        string                    `protobuf:"bytes,5,opt,name=STATUS,proto3" json:"STATUS,omitempty"`
	En_GB         int64                     `protobuf:"varint,6,opt,name=en_GB,json=enGB,proto3" json:"en_GB,omitempty"`
	No            string                    `protobuf:"bytes,7,opt,name=no,proto3" json:"no,omitempty"`
	Thing         *NonStandardMessage_Thing `protobuf:"bytes,8,opt,name=thing,proto3" json:"thing,omitempty"`
	StructField   *structpb.Struct          `protobuf:"bytes,9,opt,name=struct_field,json=structField,proto3" json:"struct_field,omitempty"`
	ValueField    *structpb.Value           `protobuf:"bytes,10,opt,name=value_field,json=valueField,proto3" json:"value_field,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NonStandardMessage) Reset() {
	*x = NonStandardMessage{}
	mi := &file_non_standart_names_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NonStandardMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NonStandardMessage) ProtoMessage() {}

func (x *NonStandardMessage) ProtoReflect() protoreflect.Message {
	mi := &file_non_standart_names_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NonStandardMessage.ProtoReflect.Descriptor instead.
func (*NonStandardMessage) Descriptor() ([]byte, []int) {
	return file_non_standart_names_proto_rawDescGZIP(), []int{0}
}

func (x *NonStandardMessage) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *NonStandardMessage) GetNum() int64 {
	if x != nil {
		return x.Num
	}
	return 0
}

func (x *NonStandardMessage) GetLineNum() int64 {
	if x != nil {
		return x.LineNum
	}
	return 0
}

func (x *NonStandardMessage) GetLangIdent() string {
	if x != nil {
		return x.LangIdent
	}
	return ""
}

func (x *NonStandardMessage) GetSTATUS() string {
	if x != nil {
		return x.STATUS
	}
	return ""
}

func (x *NonStandardMessage) GetEn_GB() int64 {
	if x != nil {
		return x.En_GB
	}
	return 0
}

func (x *NonStandardMessage) GetNo() string {
	if x != nil {
		return x.No
	}
	return ""
}

func (x *NonStandardMessage) GetThing() *NonStandardMessage_Thing {
	if x != nil {
		return x.Thing
	}
	return nil
}

func (x *NonStandardMessage) GetStructField() *structpb.Struct {
	if x != nil {
		return x.StructField
	}
	return nil
}

func (x *NonStandardMessage) GetValueField() *structpb.Value {
	if x != nil {
		return x.ValueField
	}
	return nil
}

// NonStandardMessageWithJSONNames maps odd field names to odd JSON names for maximum confusion.
type NonStandardMessageWithJSONNames struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Id represents the message identifier.
	Id            string                                 `protobuf:"bytes,1,opt,name=id,json=ID,proto3" json:"id,omitempty"`
	Num           int64                                  `protobuf:"varint,2,opt,name=Num,proto3" json:"Num,omitempty"`
	LineNum       int64                                  `protobuf:"varint,3,opt,name=line_num,json=LineNum,proto3" json:"line_num,omitempty"`
	LangIdent     string                                 `protobuf:"bytes,4,opt,name=langIdent,proto3" json:"langIdent,omitempty"`
	STATUS        string                                 `protobuf:"bytes,5,opt,name=STATUS,json=status,proto3" json:"STATUS,omitempty"`
	En_GB         int64                                  `protobuf:"varint,6,opt,name=en_GB,json=En_GB,proto3" json:"en_GB,omitempty"`
	No            string                                 `protobuf:"bytes,7,opt,name=no,json=yes,proto3" json:"no,omitempty"`
	Thing         *NonStandardMessageWithJSONNames_Thing `protobuf:"bytes,8,opt,name=thing,json=Thingy,proto3" json:"thing,omitempty"`
	StructField   *structpb.Struct                       `protobuf:"bytes,9,opt,name=struct_field,json=StructField,proto3" json:"struct_field,omitempty"`
	ValueField    *structpb.Value                        `protobuf:"bytes,10,opt,name=value_field,json=ValueField,proto3" json:"value_field,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NonStandardMessageWithJSONNames) Reset() {
	*x = NonStandardMessageWithJSONNames{}
	mi := &file_non_standart_names_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NonStandardMessageWithJSONNames) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NonStandardMessageWithJSONNames) ProtoMessage() {}

func (x *NonStandardMessageWithJSONNames) ProtoReflect() protoreflect.Message {
	mi := &file_non_standart_names_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NonStandardMessageWithJSONNames.ProtoReflect.Descriptor instead.
func (*NonStandardMessageWithJSONNames) Descriptor() ([]byte, []int) {
	return file_non_standart_names_proto_rawDescGZIP(), []int{1}
}

func (x *NonStandardMessageWithJSONNames) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *NonStandardMessageWithJSONNames) GetNum() int64 {
	if x != nil {
		return x.Num
	}
	return 0
}

func (x *NonStandardMessageWithJSONNames) GetLineNum() int64 {
	if x != nil {
		return x.LineNum
	}
	return 0
}

func (x *NonStandardMessageWithJSONNames) GetLangIdent() string {
	if x != nil {
		return x.LangIdent
	}
	return ""
}

func (x *NonStandardMessageWithJSONNames) GetSTATUS() string {
	if x != nil {
		return x.STATUS
	}
	return ""
}

func (x *NonStandardMessageWithJSONNames) GetEn_GB() int64 {
	if x != nil {
		return x.En_GB
	}
	return 0
}

func (x *NonStandardMessageWithJSONNames) GetNo() string {
	if x != nil {
		return x.No
	}
	return ""
}

func (x *NonStandardMessageWithJSONNames) GetThing() *NonStandardMessageWithJSONNames_Thing {
	if x != nil {
		return x.Thing
	}
	return nil
}

func (x *NonStandardMessageWithJSONNames) GetStructField() *structpb.Struct {
	if x != nil {
		return x.StructField
	}
	return nil
}

func (x *NonStandardMessageWithJSONNames) GetValueField() *structpb.Value {
	if x != nil {
		return x.ValueField
	}
	return nil
}

type NonStandardMessage_Thing struct {
	state         protoimpl.MessageState             `protogen:"open.v1"`
	SubThing      *NonStandardMessage_Thing_SubThing `protobuf:"bytes,1,opt,name=subThing,proto3" json:"subThing,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NonStandardMessage_Thing) Reset() {
	*x = NonStandardMessage_Thing{}
	mi := &file_non_standart_names_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NonStandardMessage_Thing) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NonStandardMessage_Thing) ProtoMessage() {}

func (x *NonStandardMessage_Thing) ProtoReflect() protoreflect.Message {
	mi := &file_non_standart_names_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NonStandardMessage_Thing.ProtoReflect.Descriptor instead.
func (*NonStandardMessage_Thing) Descriptor() ([]byte, []int) {
	return file_non_standart_names_proto_rawDescGZIP(), []int{0, 0}
}

func (x *NonStandardMessage_Thing) GetSubThing() *NonStandardMessage_Thing_SubThing {
	if x != nil {
		return x.SubThing
	}
	return nil
}

type NonStandardMessage_Thing_SubThing struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SubValue      string                 `protobuf:"bytes,1,opt,name=sub_value,json=subValue,proto3" json:"sub_value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NonStandardMessage_Thing_SubThing) Reset() {
	*x = NonStandardMessage_Thing_SubThing{}
	mi := &file_non_standart_names_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NonStandardMessage_Thing_SubThing) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NonStandardMessage_Thing_SubThing) ProtoMessage() {}

func (x *NonStandardMessage_Thing_SubThing) ProtoReflect() protoreflect.Message {
	mi := &file_non_standart_names_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NonStandardMessage_Thing_SubThing.ProtoReflect.Descriptor instead.
func (*NonStandardMessage_Thing_SubThing) Descriptor() ([]byte, []int) {
	return file_non_standart_names_proto_rawDescGZIP(), []int{0, 0, 0}
}

func (x *NonStandardMessage_Thing_SubThing) GetSubValue() string {
	if x != nil {
		return x.SubValue
	}
	return ""
}

type NonStandardMessageWithJSONNames_Thing struct {
	state         protoimpl.MessageState                          `protogen:"open.v1"`
	SubThing      *NonStandardMessageWithJSONNames_Thing_SubThing `protobuf:"bytes,1,opt,name=subThing,json=SubThing,proto3" json:"subThing,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NonStandardMessageWithJSONNames_Thing) Reset() {
	*x = NonStandardMessageWithJSONNames_Thing{}
	mi := &file_non_standart_names_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NonStandardMessageWithJSONNames_Thing) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NonStandardMessageWithJSONNames_Thing) ProtoMessage() {}

func (x *NonStandardMessageWithJSONNames_Thing) ProtoReflect() protoreflect.Message {
	mi := &file_non_standart_names_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NonStandardMessageWithJSONNames_Thing.ProtoReflect.Descriptor instead.
func (*NonStandardMessageWithJSONNames_Thing) Descriptor() ([]byte, []int) {
	return file_non_standart_names_proto_rawDescGZIP(), []int{1, 0}
}

func (x *NonStandardMessageWithJSONNames_Thing) GetSubThing() *NonStandardMessageWithJSONNames_Thing_SubThing {
	if x != nil {
		return x.SubThing
	}
	return nil
}

type NonStandardMessageWithJSONNames_Thing_SubThing struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SubValue      string                 `protobuf:"bytes,1,opt,name=sub_value,json=sub_Value,proto3" json:"sub_value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NonStandardMessageWithJSONNames_Thing_SubThing) Reset() {
	*x = NonStandardMessageWithJSONNames_Thing_SubThing{}
	mi := &file_non_standart_names_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NonStandardMessageWithJSONNames_Thing_SubThing) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NonStandardMessageWithJSONNames_Thing_SubThing) ProtoMessage() {}

func (x *NonStandardMessageWithJSONNames_Thing_SubThing) ProtoReflect() protoreflect.Message {
	mi := &file_non_standart_names_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NonStandardMessageWithJSONNames_Thing_SubThing.ProtoReflect.Descriptor instead.
func (*NonStandardMessageWithJSONNames_Thing_SubThing) Descriptor() ([]byte, []int) {
	return file_non_standart_names_proto_rawDescGZIP(), []int{1, 0, 0}
}

func (x *NonStandardMessageWithJSONNames_Thing_SubThing) GetSubValue() string {
	if x != nil {
		return x.SubValue
	}
	return ""
}

var File_non_standart_names_proto protoreflect.FileDescriptor

const file_non_standart_names_proto_rawDesc = "" +
	"\n" +
	"\x18non_standart_names.proto\x12\x1cgrpc.gateway.internal.testpb\x1a google/protobuf/field_mask.proto\x1a\x1cgoogle/protobuf/struct.proto\"\xff\x03\n" +
	"\x12NonStandardMessage\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x10\n" +
	"\x03Num\x18\x02 \x01(\x03R\x03Num\x12\x19\n" +
	"\bline_num\x18\x03 \x01(\x03R\alineNum\x12\x1c\n" +
	"\tlangIdent\x18\x04 \x01(\tR\tlangIdent\x12\x16\n" +
	"\x06STATUS\x18\x05 \x01(\tR\x06STATUS\x12\x13\n" +
	"\x05en_GB\x18\x06 \x01(\x03R\x04enGB\x12\x0e\n" +
	"\x02no\x18\a \x01(\tR\x02no\x12L\n" +
	"\x05thing\x18\b \x01(\v26.grpc.gateway.internal.testpb.NonStandardMessage.ThingR\x05thing\x12:\n" +
	"\fstruct_field\x18\t \x01(\v2\x17.google.protobuf.StructR\vstructField\x127\n" +
	"\vvalue_field\x18\n" +
	" \x01(\v2\x16.google.protobuf.ValueR\n" +
	"valueField\x1a\x8d\x01\n" +
	"\x05Thing\x12[\n" +
	"\bsubThing\x18\x01 \x01(\v2?.grpc.gateway.internal.testpb.NonStandardMessage.Thing.SubThingR\bsubThing\x1a'\n" +
	"\bSubThing\x12\x1b\n" +
	"\tsub_value\x18\x01 \x01(\tR\bsubValue\"\xaa\x04\n" +
	"\x1fNonStandardMessageWithJSONNames\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02ID\x12\x10\n" +
	"\x03Num\x18\x02 \x01(\x03R\x03Num\x12\x19\n" +
	"\bline_num\x18\x03 \x01(\x03R\aLineNum\x12\x1c\n" +
	"\tlangIdent\x18\x04 \x01(\tR\tlangIdent\x12\x16\n" +
	"\x06STATUS\x18\x05 \x01(\tR\x06status\x12\x14\n" +
	"\x05en_GB\x18\x06 \x01(\x03R\x05En_GB\x12\x0f\n" +
	"\x02no\x18\a \x01(\tR\x03yes\x12Z\n" +
	"\x05thing\x18\b \x01(\v2C.grpc.gateway.internal.testpb.NonStandardMessageWithJSONNames.ThingR\x06Thingy\x12:\n" +
	"\fstruct_field\x18\t \x01(\v2\x17.google.protobuf.StructR\vStructField\x127\n" +
	"\vvalue_field\x18\n" +
	" \x01(\v2\x16.google.protobuf.ValueR\n" +
	"ValueField\x1a\x9b\x01\n" +
	"\x05Thing\x12h\n" +
	"\bsubThing\x18\x01 \x01(\v2L.grpc.gateway.internal.testpb.NonStandardMessageWithJSONNames.Thing.SubThingR\bSubThing\x1a(\n" +
	"\bSubThing\x12\x1c\n" +
	"\tsub_value\x18\x01 \x01(\tR\tsub_ValueB5Z3github.com/meshapi/grpc-api-gateway/internal/testpbb\x06proto3"

var (
	file_non_standart_names_proto_rawDescOnce sync.Once
	file_non_standart_names_proto_rawDescData []byte
)

func file_non_standart_names_proto_rawDescGZIP() []byte {
	file_non_standart_names_proto_rawDescOnce.Do(func() {
		file_non_standart_names_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_non_standart_names_proto_rawDesc), len(file_non_standart_names_proto_rawDesc)))
	})
	return file_non_standart_names_proto_rawDescData
}

var file_non_standart_names_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_non_standart_names_proto_goTypes = []any{
	(*NonStandardMessage)(nil),                             // 0: grpc.gateway.internal.testpb.NonStandardMessage
	(*NonStandardMessageWithJSONNames)(nil),                // 1: grpc.gateway.internal.testpb.NonStandardMessageWithJSONNames
	(*NonStandardMessage_Thing)(nil),                       // 2: grpc.gateway.internal.testpb.NonStandardMessage.Thing
	(*NonStandardMessage_Thing_SubThing)(nil),              // 3: grpc.gateway.internal.testpb.NonStandardMessage.Thing.SubThing
	(*NonStandardMessageWithJSONNames_Thing)(nil),          // 4: grpc.gateway.internal.testpb.NonStandardMessageWithJSONNames.Thing
	(*NonStandardMessageWithJSONNames_Thing_SubThing)(nil), // 5: grpc.gateway.internal.testpb.NonStandardMessageWithJSONNames.Thing.SubThing
	(*structpb.Struct)(nil),                                // 6: google.protobuf.Struct
	(*structpb.Value)(nil),                                 // 7: google.protobuf.Value
}
var file_non_standart_names_proto_depIdxs = []int32{
	2, // 0: grpc.gateway.internal.testpb.NonStandardMessage.thing:type_name -> grpc.gateway.internal.testpb.NonStandardMessage.Thing
	6, // 1: grpc.gateway.internal.testpb.NonStandardMessage.struct_field:type_name -> google.protobuf.Struct
	7, // 2: grpc.gateway.internal.testpb.NonStandardMessage.value_field:type_name -> google.protobuf.Value
	4, // 3: grpc.gateway.internal.testpb.NonStandardMessageWithJSONNames.thing:type_name -> grpc.gateway.internal.testpb.NonStandardMessageWithJSONNames.Thing
	6, // 4: grpc.gateway.internal.testpb.NonStandardMessageWithJSONNames.struct_field:type_name -> google.protobuf.Struct
	7, // 5: grpc.gateway.internal.testpb.NonStandardMessageWithJSONNames.value_field:type_name -> google.protobuf.Value
	3, // 6: grpc.gateway.internal.testpb.NonStandardMessage.Thing.subThing:type_name -> grpc.gateway.internal.testpb.NonStandardMessage.Thing.SubThing
	5, // 7: grpc.gateway.internal.testpb.NonStandardMessageWithJSONNames.Thing.subThing:type_name -> grpc.gateway.internal.testpb.NonStandardMessageWithJSONNames.Thing.SubThing
	8, // [8:8] is the sub-list for method output_type
	8, // [8:8] is the sub-list for method input_type
	8, // [8:8] is the sub-list for extension type_name
	8, // [8:8] is the sub-list for extension extendee
	0, // [0:8] is the sub-list for field type_name
}

func init() { file_non_standart_names_proto_init() }
func file_non_standart_names_proto_init() {
	if File_non_standart_names_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_non_standart_names_proto_rawDesc), len(file_non_standart_names_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_non_standart_names_proto_goTypes,
		DependencyIndexes: file_non_standart_names_proto_depIdxs,
		MessageInfos:      file_non_standart_names_proto_msgTypes,
	}.Build()
	File_non_standart_names_proto = out.File
	file_non_standart_names_proto_goTypes = nil
	file_non_standart_names_proto_depIdxs = nil
}
