// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.9
// 	protoc        (unknown)
// source: test.proto

package testpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	anypb "google.golang.org/protobuf/types/known/anypb"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	fieldmaskpb "google.golang.org/protobuf/types/known/fieldmaskpb"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// NumericEnum is one or zero.
type NumericEnum int32

const (
	// ZERO means 0
	NumericEnum_ZERO NumericEnum = 0
	// ONE means 1
	NumericEnum_ONE NumericEnum = 1
)

// Enum value maps for NumericEnum.
var (
	NumericEnum_name = map[int32]string{
		0: "ZERO",
		1: "ONE",
	}
	NumericEnum_value = map[string]int32{
		"ZERO": 0,
		"ONE":  1,
	}
)

func (x NumericEnum) Enum() *NumericEnum {
	p := new(NumericEnum)
	*p = x
	return p
}

func (x NumericEnum) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (NumericEnum) Descriptor() protoreflect.EnumDescriptor {
	return file_test_proto_enumTypes[0].Descriptor()
}

func (NumericEnum) Type() protoreflect.EnumType {
	return &file_test_proto_enumTypes[0]
}

func (x NumericEnum) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use NumericEnum.Descriptor instead.
func (NumericEnum) EnumDescriptor() ([]byte, []int) {
	return file_test_proto_rawDescGZIP(), []int{0}
}

// DeepEnum is one or zero.
type ABitOfEverything_Nested_DeepEnum int32

const (
	// FALSE is false.
	ABitOfEverything_Nested_FALSE ABitOfEverything_Nested_DeepEnum = 0
	// TRUE is true.
	ABitOfEverything_Nested_TRUE ABitOfEverything_Nested_DeepEnum = 1
)

// Enum value maps for ABitOfEverything_Nested_DeepEnum.
var (
	ABitOfEverything_Nested_DeepEnum_name = map[int32]string{
		0: "FALSE",
		1: "TRUE",
	}
	ABitOfEverything_Nested_DeepEnum_value = map[string]int32{
		"FALSE": 0,
		"TRUE":  1,
	}
)

func (x ABitOfEverything_Nested_DeepEnum) Enum() *ABitOfEverything_Nested_DeepEnum {
	p := new(ABitOfEverything_Nested_DeepEnum)
	*p = x
	return p
}

func (x ABitOfEverything_Nested_DeepEnum) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ABitOfEverything_Nested_DeepEnum) Descriptor() protoreflect.EnumDescriptor {
	return file_test_proto_enumTypes[1].Descriptor()
}

func (ABitOfEverything_Nested_DeepEnum) Type() protoreflect.EnumType {
	return &file_test_proto_enumTypes[1]
}

func (x ABitOfEverything_Nested_DeepEnum) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ABitOfEverything_Nested_DeepEnum.Descriptor instead.
func (ABitOfEverything_Nested_DeepEnum) EnumDescriptor() ([]byte, []int) {
	return file_test_proto_rawDescGZIP(), []int{0, 0, 0}
}

type RepeatedResponseBodyOut_Response_ResponseType int32

const (
	// UNKNOWN
	RepeatedResponseBodyOut_Response_UNKNOWN RepeatedResponseBodyOut_Response_ResponseType = 0
	// A is 1
	RepeatedResponseBodyOut_Response_A RepeatedResponseBodyOut_Response_ResponseType = 1
	// B is 2
	RepeatedResponseBodyOut_Response_B RepeatedResponseBodyOut_Response_ResponseType = 2
)

// Enum value maps for RepeatedResponseBodyOut_Response_ResponseType.
var (
	RepeatedResponseBodyOut_Response_ResponseType_name = map[int32]string{
		0: "UNKNOWN",
		1: "A",
		2: "B",
	}
	RepeatedResponseBodyOut_Response_ResponseType_value = map[string]int32{
		"UNKNOWN": 0,
		"A":       1,
		"B":       2,
	}
)

func (x RepeatedResponseBodyOut_Response_ResponseType) Enum() *RepeatedResponseBodyOut_Response_ResponseType {
	p := new(RepeatedResponseBodyOut_Response_ResponseType)
	*p = x
	return p
}

func (x RepeatedResponseBodyOut_Response_ResponseType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (RepeatedResponseBodyOut_Response_ResponseType) Descriptor() protoreflect.EnumDescriptor {
	return file_test_proto_enumTypes[2].Descriptor()
}

func (RepeatedResponseBodyOut_Response_ResponseType) Type() protoreflect.EnumType {
	return &file_test_proto_enumTypes[2]
}

func (x RepeatedResponseBodyOut_Response_ResponseType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use RepeatedResponseBodyOut_Response_ResponseType.Descriptor instead.
func (RepeatedResponseBodyOut_Response_ResponseType) EnumDescriptor() ([]byte, []int) {
	return file_test_proto_rawDescGZIP(), []int{2, 0, 0}
}

type ABitOfEverything struct {
	state               protoimpl.MessageState     `protogen:"open.v1"`
	SingleNested        *ABitOfEverything_Nested   `protobuf:"bytes,25,opt,name=single_nested,json=singleNested,proto3" json:"single_nested,omitempty"`
	Uuid                string                     `protobuf:"bytes,1,opt,name=uuid,proto3" json:"uuid,omitempty"`
	Nested              []*ABitOfEverything_Nested `protobuf:"bytes,2,rep,name=nested,proto3" json:"nested,omitempty"`
	FloatValue          float32                    `protobuf:"fixed32,3,opt,name=float_value,json=floatValue,proto3" json:"float_value,omitempty"`
	DoubleValue         float64                    `protobuf:"fixed64,4,opt,name=double_value,json=doubleValue,proto3" json:"double_value,omitempty"`
	Int64Value          int64                      `protobuf:"varint,5,opt,name=int64_value,json=int64Value,proto3" json:"int64_value,omitempty"`
	Uint64Value         uint64                     `protobuf:"varint,6,opt,name=uint64_value,json=uint64Value,proto3" json:"uint64_value,omitempty"`
	Int32Value          int32                      `protobuf:"varint,7,opt,name=int32_value,json=int32Value,proto3" json:"int32_value,omitempty"`
	Fixed64Value        uint64                     `protobuf:"fixed64,8,opt,name=fixed64_value,json=fixed64Value,proto3" json:"fixed64_value,omitempty"`
	Fixed32Value        uint32                     `protobuf:"fixed32,9,opt,name=fixed32_value,json=fixed32Value,proto3" json:"fixed32_value,omitempty"`
	BoolValue           bool                       `protobuf:"varint,10,opt,name=bool_value,json=boolValue,proto3" json:"bool_value,omitempty"`
	StringValue         string                     `protobuf:"bytes,11,opt,name=string_value,json=stringValue,proto3" json:"string_value,omitempty"`
	BytesValue          []byte                     `protobuf:"bytes,29,opt,name=bytes_value,json=bytesValue,proto3" json:"bytes_value,omitempty"`
	Uint32Value         uint32                     `protobuf:"varint,13,opt,name=uint32_value,json=uint32Value,proto3" json:"uint32_value,omitempty"`
	EnumValue           NumericEnum                `protobuf:"varint,14,opt,name=enum_value,json=enumValue,proto3,enum=grpc.gateway.internal.testpb.NumericEnum" json:"enum_value,omitempty"`
	Sfixed32Value       int32                      `protobuf:"fixed32,15,opt,name=sfixed32_value,json=sfixed32Value,proto3" json:"sfixed32_value,omitempty"`
	Sfixed64Value       int64                      `protobuf:"fixed64,16,opt,name=sfixed64_value,json=sfixed64Value,proto3" json:"sfixed64_value,omitempty"`
	Sint32Value         int32                      `protobuf:"zigzag32,17,opt,name=sint32_value,json=sint32Value,proto3" json:"sint32_value,omitempty"`
	Sint64Value         int64                      `protobuf:"zigzag64,18,opt,name=sint64_value,json=sint64Value,proto3" json:"sint64_value,omitempty"`
	RepeatedStringValue []string                   `protobuf:"bytes,19,rep,name=repeated_string_value,json=repeatedStringValue,proto3" json:"repeated_string_value,omitempty"`
	// Types that are valid to be assigned to OneofValue:
	//
	//	*ABitOfEverything_OneofEmpty
	//	*ABitOfEverything_OneofString
	OneofValue               isABitOfEverything_OneofValue       `protobuf_oneof:"oneof_value"`
	MapValue                 map[string]NumericEnum              `protobuf:"bytes,22,rep,name=map_value,json=mapValue,proto3" json:"map_value,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"varint,2,opt,name=value,enum=grpc.gateway.internal.testpb.NumericEnum"`
	MappedStringValue        map[string]string                   `protobuf:"bytes,23,rep,name=mapped_string_value,json=mappedStringValue,proto3" json:"mapped_string_value,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	MappedNestedValue        map[string]*ABitOfEverything_Nested `protobuf:"bytes,24,rep,name=mapped_nested_value,json=mappedNestedValue,proto3" json:"mapped_nested_value,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	NonConventionalNameValue string                              `protobuf:"bytes,26,opt,name=nonConventionalNameValue,proto3" json:"nonConventionalNameValue,omitempty"`
	TimestampValue           *timestamppb.Timestamp              `protobuf:"bytes,27,opt,name=timestamp_value,json=timestampValue,proto3" json:"timestamp_value,omitempty"`
	// repeated enum value. it is comma-separated in query
	RepeatedEnumValue []NumericEnum `protobuf:"varint,28,rep,packed,name=repeated_enum_value,json=repeatedEnumValue,proto3,enum=grpc.gateway.internal.testpb.NumericEnum" json:"repeated_enum_value,omitempty"`
	// repeated numeric enum comment (This comment is overridden by the field
	// annotation)
	RepeatedEnumAnnotation []NumericEnum `protobuf:"varint,32,rep,packed,name=repeated_enum_annotation,json=repeatedEnumAnnotation,proto3,enum=grpc.gateway.internal.testpb.NumericEnum" json:"repeated_enum_annotation,omitempty"`
	// numeric enum comment (This comment is overridden by the field annotation)
	EnumValueAnnotation NumericEnum `protobuf:"varint,33,opt,name=enum_value_annotation,json=enumValueAnnotation,proto3,enum=grpc.gateway.internal.testpb.NumericEnum" json:"enum_value_annotation,omitempty"`
	// repeated string comment (This comment is overridden by the field
	// annotation)
	RepeatedStringAnnotation []string `protobuf:"bytes,34,rep,name=repeated_string_annotation,json=repeatedStringAnnotation,proto3" json:"repeated_string_annotation,omitempty"`
	// repeated nested object comment (This comment is overridden by the field
	// annotation)
	RepeatedNestedAnnotation []*ABitOfEverything_Nested `protobuf:"bytes,35,rep,name=repeated_nested_annotation,json=repeatedNestedAnnotation,proto3" json:"repeated_nested_annotation,omitempty"`
	// nested object comments (This comment is overridden by the field annotation)
	NestedAnnotation  *ABitOfEverything_Nested `protobuf:"bytes,36,opt,name=nested_annotation,json=nestedAnnotation,proto3" json:"nested_annotation,omitempty"`
	Int64OverrideType int64                    `protobuf:"varint,37,opt,name=int64_override_type,json=int64OverrideType,proto3" json:"int64_override_type,omitempty"`
	Anytype           *anypb.Any               `protobuf:"bytes,38,opt,name=anytype,proto3" json:"anytype,omitempty"`
	RepeatedAnytype   []*anypb.Any             `protobuf:"bytes,39,rep,name=repeated_anytype,json=repeatedAnytype,proto3" json:"repeated_anytype,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *ABitOfEverything) Reset() {
	*x = ABitOfEverything{}
	mi := &file_test_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ABitOfEverything) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ABitOfEverything) ProtoMessage() {}

func (x *ABitOfEverything) ProtoReflect() protoreflect.Message {
	mi := &file_test_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ABitOfEverything.ProtoReflect.Descriptor instead.
func (*ABitOfEverything) Descriptor() ([]byte, []int) {
	return file_test_proto_rawDescGZIP(), []int{0}
}

func (x *ABitOfEverything) GetSingleNested() *ABitOfEverything_Nested {
	if x != nil {
		return x.SingleNested
	}
	return nil
}

func (x *ABitOfEverything) GetUuid() string {
	if x != nil {
		return x.Uuid
	}
	return ""
}

func (x *ABitOfEverything) GetNested() []*ABitOfEverything_Nested {
	if x != nil {
		return x.Nested
	}
	return nil
}

func (x *ABitOfEverything) GetFloatValue() float32 {
	if x != nil {
		return x.FloatValue
	}
	return 0
}

func (x *ABitOfEverything) GetDoubleValue() float64 {
	if x != nil {
		return x.DoubleValue
	}
	return 0
}

func (x *ABitOfEverything) GetInt64Value() int64 {
	if x != nil {
		return x.Int64Value
	}
	return 0
}

func (x *ABitOfEverything) GetUint64Value() uint64 {
	if x != nil {
		return x.Uint64Value
	}
	return 0
}

func (x *ABitOfEverything) GetInt32Value() int32 {
	if x != nil {
		return x.Int32Value
	}
	return 0
}

func (x *ABitOfEverything) GetFixed64Value() uint64 {
	if x != nil {
		return x.Fixed64Value
	}
	return 0
}

func (x *ABitOfEverything) GetFixed32Value() uint32 {
	if x != nil {
		return x.Fixed32Value
	}
	return 0
}

func (x *ABitOfEverything) GetBoolValue() bool {
	if x != nil {
		return x.BoolValue
	}
	return false
}

func (x *ABitOfEverything) GetStringValue() string {
	if x != nil {
		return x.StringValue
	}
	return ""
}

func (x *ABitOfEverything) GetBytesValue() []byte {
	if x != nil {
		return x.BytesValue
	}
	return nil
}

func (x *ABitOfEverything) GetUint32Value() uint32 {
	if x != nil {
		return x.Uint32Value
	}
	return 0
}

func (x *ABitOfEverything) GetEnumValue() NumericEnum {
	if x != nil {
		return x.EnumValue
	}
	return NumericEnum_ZERO
}

func (x *ABitOfEverything) GetSfixed32Value() int32 {
	if x != nil {
		return x.Sfixed32Value
	}
	return 0
}

func (x *ABitOfEverything) GetSfixed64Value() int64 {
	if x != nil {
		return x.Sfixed64Value
	}
	return 0
}

func (x *ABitOfEverything) GetSint32Value() int32 {
	if x != nil {
		return x.Sint32Value
	}
	return 0
}

func (x *ABitOfEverything) GetSint64Value() int64 {
	if x != nil {
		return x.Sint64Value
	}
	return 0
}

func (x *ABitOfEverything) GetRepeatedStringValue() []string {
	if x != nil {
		return x.RepeatedStringValue
	}
	return nil
}

func (x *ABitOfEverything) GetOneofValue() isABitOfEverything_OneofValue {
	if x != nil {
		return x.OneofValue
	}
	return nil
}

func (x *ABitOfEverything) GetOneofEmpty() *emptypb.Empty {
	if x != nil {
		if x, ok := x.OneofValue.(*ABitOfEverything_OneofEmpty); ok {
			return x.OneofEmpty
		}
	}
	return nil
}

func (x *ABitOfEverything) GetOneofString() string {
	if x != nil {
		if x, ok := x.OneofValue.(*ABitOfEverything_OneofString); ok {
			return x.OneofString
		}
	}
	return ""
}

func (x *ABitOfEverything) GetMapValue() map[string]NumericEnum {
	if x != nil {
		return x.MapValue
	}
	return nil
}

func (x *ABitOfEverything) GetMappedStringValue() map[string]string {
	if x != nil {
		return x.MappedStringValue
	}
	return nil
}

func (x *ABitOfEverything) GetMappedNestedValue() map[string]*ABitOfEverything_Nested {
	if x != nil {
		return x.MappedNestedValue
	}
	return nil
}

func (x *ABitOfEverything) GetNonConventionalNameValue() string {
	if x != nil {
		return x.NonConventionalNameValue
	}
	return ""
}

func (x *ABitOfEverything) GetTimestampValue() *timestamppb.Timestamp {
	if x != nil {
		return x.TimestampValue
	}
	return nil
}

func (x *ABitOfEverything) GetRepeatedEnumValue() []NumericEnum {
	if x != nil {
		return x.RepeatedEnumValue
	}
	return nil
}

func (x *ABitOfEverything) GetRepeatedEnumAnnotation() []NumericEnum {
	if x != nil {
		return x.RepeatedEnumAnnotation
	}
	return nil
}

func (x *ABitOfEverything) GetEnumValueAnnotation() NumericEnum {
	if x != nil {
		return x.EnumValueAnnotation
	}
	return NumericEnum_ZERO
}

func (x *ABitOfEverything) GetRepeatedStringAnnotation() []string {
	if x != nil {
		return x.RepeatedStringAnnotation
	}
	return nil
}

func (x *ABitOfEverything) GetRepeatedNestedAnnotation() []*ABitOfEverything_Nested {
	if x != nil {
		return x.RepeatedNestedAnnotation
	}
	return nil
}

func (x *ABitOfEverything) GetNestedAnnotation() *ABitOfEverything_Nested {
	if x != nil {
		return x.NestedAnnotation
	}
	return nil
}

func (x *ABitOfEverything) GetInt64OverrideType() int64 {
	if x != nil {
		return x.Int64OverrideType
	}
	return 0
}

func (x *ABitOfEverything) GetAnytype() *anypb.Any {
	if x != nil {
		return x.Anytype
	}
	return nil
}

func (x *ABitOfEverything) GetRepeatedAnytype() []*anypb.Any {
	if x != nil {
		return x.RepeatedAnytype
	}
	return nil
}

type isABitOfEverything_OneofValue interface {
	isABitOfEverything_OneofValue()
}

type ABitOfEverything_OneofEmpty struct {
	OneofEmpty *emptypb.Empty `protobuf:"bytes,20,opt,name=oneof_empty,json=oneofEmpty,proto3,oneof"`
}

type ABitOfEverything_OneofString struct {
	OneofString string `protobuf:"bytes,21,opt,name=oneof_string,json=oneofString,proto3,oneof"`
}

func (*ABitOfEverything_OneofEmpty) isABitOfEverything_OneofValue() {}

func (*ABitOfEverything_OneofString) isABitOfEverything_OneofValue() {}

type ResponseBodyOut struct {
	state         protoimpl.MessageState    `protogen:"open.v1"`
	Response      *ResponseBodyOut_Response `protobuf:"bytes,2,opt,name=response,proto3" json:"response,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ResponseBodyOut) Reset() {
	*x = ResponseBodyOut{}
	mi := &file_test_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResponseBodyOut) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResponseBodyOut) ProtoMessage() {}

func (x *ResponseBodyOut) ProtoReflect() protoreflect.Message {
	mi := &file_test_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResponseBodyOut.ProtoReflect.Descriptor instead.
func (*ResponseBodyOut) Descriptor() ([]byte, []int) {
	return file_test_proto_rawDescGZIP(), []int{1}
}

func (x *ResponseBodyOut) GetResponse() *ResponseBodyOut_Response {
	if x != nil {
		return x.Response
	}
	return nil
}

type RepeatedResponseBodyOut struct {
	state         protoimpl.MessageState              `protogen:"open.v1"`
	Response      []*RepeatedResponseBodyOut_Response `protobuf:"bytes,2,rep,name=response,proto3" json:"response,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RepeatedResponseBodyOut) Reset() {
	*x = RepeatedResponseBodyOut{}
	mi := &file_test_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RepeatedResponseBodyOut) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RepeatedResponseBodyOut) ProtoMessage() {}

func (x *RepeatedResponseBodyOut) ProtoReflect() protoreflect.Message {
	mi := &file_test_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RepeatedResponseBodyOut.ProtoReflect.Descriptor instead.
func (*RepeatedResponseBodyOut) Descriptor() ([]byte, []int) {
	return file_test_proto_rawDescGZIP(), []int{2}
}

func (x *RepeatedResponseBodyOut) GetResponse() []*RepeatedResponseBodyOut_Response {
	if x != nil {
		return x.Response
	}
	return nil
}

type UpdateMessage struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	UpdateMask       *fieldmaskpb.FieldMask `protobuf:"bytes,1,opt,name=update_mask,json=updateMask,proto3" json:"update_mask,omitempty"`
	ABitOfEverything *ABitOfEverything      `protobuf:"bytes,2,opt,name=a_bit_of_everything,json=aBitOfEverything,proto3" json:"a_bit_of_everything,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *UpdateMessage) Reset() {
	*x = UpdateMessage{}
	mi := &file_test_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateMessage) ProtoMessage() {}

func (x *UpdateMessage) ProtoReflect() protoreflect.Message {
	mi := &file_test_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateMessage.ProtoReflect.Descriptor instead.
func (*UpdateMessage) Descriptor() ([]byte, []int) {
	return file_test_proto_rawDescGZIP(), []int{3}
}

func (x *UpdateMessage) GetUpdateMask() *fieldmaskpb.FieldMask {
	if x != nil {
		return x.UpdateMask
	}
	return nil
}

func (x *UpdateMessage) GetABitOfEverything() *ABitOfEverything {
	if x != nil {
		return x.ABitOfEverything
	}
	return nil
}

type NestedOuter struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	One           *NestedOne             `protobuf:"bytes,1,opt,name=one,proto3" json:"one,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NestedOuter) Reset() {
	*x = NestedOuter{}
	mi := &file_test_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NestedOuter) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NestedOuter) ProtoMessage() {}

func (x *NestedOuter) ProtoReflect() protoreflect.Message {
	mi := &file_test_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NestedOuter.ProtoReflect.Descriptor instead.
func (*NestedOuter) Descriptor() ([]byte, []int) {
	return file_test_proto_rawDescGZIP(), []int{4}
}

func (x *NestedOuter) GetOne() *NestedOne {
	if x != nil {
		return x.One
	}
	return nil
}

type NestedOne struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Two           *NestedTwo             `protobuf:"bytes,1,opt,name=two,proto3" json:"two,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NestedOne) Reset() {
	*x = NestedOne{}
	mi := &file_test_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NestedOne) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NestedOne) ProtoMessage() {}

func (x *NestedOne) ProtoReflect() protoreflect.Message {
	mi := &file_test_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NestedOne.ProtoReflect.Descriptor instead.
func (*NestedOne) Descriptor() ([]byte, []int) {
	return file_test_proto_rawDescGZIP(), []int{5}
}

func (x *NestedOne) GetTwo() *NestedTwo {
	if x != nil {
		return x.Two
	}
	return nil
}

type NestedTwo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Three         *NestedThree           `protobuf:"bytes,1,opt,name=three,proto3" json:"three,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NestedTwo) Reset() {
	*x = NestedTwo{}
	mi := &file_test_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NestedTwo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NestedTwo) ProtoMessage() {}

func (x *NestedTwo) ProtoReflect() protoreflect.Message {
	mi := &file_test_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NestedTwo.ProtoReflect.Descriptor instead.
func (*NestedTwo) Descriptor() ([]byte, []int) {
	return file_test_proto_rawDescGZIP(), []int{6}
}

func (x *NestedTwo) GetThree() *NestedThree {
	if x != nil {
		return x.Three
	}
	return nil
}

type NestedThree struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	A             bool                   `protobuf:"varint,1,opt,name=a,proto3" json:"a,omitempty"`
	B             bool                   `protobuf:"varint,2,opt,name=b,proto3" json:"b,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NestedThree) Reset() {
	*x = NestedThree{}
	mi := &file_test_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NestedThree) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NestedThree) ProtoMessage() {}

func (x *NestedThree) ProtoReflect() protoreflect.Message {
	mi := &file_test_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NestedThree.ProtoReflect.Descriptor instead.
func (*NestedThree) Descriptor() ([]byte, []int) {
	return file_test_proto_rawDescGZIP(), []int{7}
}

func (x *NestedThree) GetA() bool {
	if x != nil {
		return x.A
	}
	return false
}

func (x *NestedThree) GetB() bool {
	if x != nil {
		return x.B
	}
	return false
}

type UpdateNestedRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Nested        *NestedOuter           `protobuf:"bytes,1,opt,name=nested,proto3" json:"nested,omitempty"`
	UpdateMask    *fieldmaskpb.FieldMask `protobuf:"bytes,2,opt,name=update_mask,json=updateMask,proto3" json:"update_mask,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateNestedRequest) Reset() {
	*x = UpdateNestedRequest{}
	mi := &file_test_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateNestedRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateNestedRequest) ProtoMessage() {}

func (x *UpdateNestedRequest) ProtoReflect() protoreflect.Message {
	mi := &file_test_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateNestedRequest.ProtoReflect.Descriptor instead.
func (*UpdateNestedRequest) Descriptor() ([]byte, []int) {
	return file_test_proto_rawDescGZIP(), []int{8}
}

func (x *UpdateNestedRequest) GetNested() *NestedOuter {
	if x != nil {
		return x.Nested
	}
	return nil
}

func (x *UpdateNestedRequest) GetUpdateMask() *fieldmaskpb.FieldMask {
	if x != nil {
		return x.UpdateMask
	}
	return nil
}

// Embedded represents a message embedded in SimpleMessage.
type Embedded struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Mark:
	//
	//	*Embedded_Progress
	//	*Embedded_Note
	Mark          isEmbedded_Mark `protobuf_oneof:"mark"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Embedded) Reset() {
	*x = Embedded{}
	mi := &file_test_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Embedded) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Embedded) ProtoMessage() {}

func (x *Embedded) ProtoReflect() protoreflect.Message {
	mi := &file_test_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Embedded.ProtoReflect.Descriptor instead.
func (*Embedded) Descriptor() ([]byte, []int) {
	return file_test_proto_rawDescGZIP(), []int{9}
}

func (x *Embedded) GetMark() isEmbedded_Mark {
	if x != nil {
		return x.Mark
	}
	return nil
}

func (x *Embedded) GetProgress() int64 {
	if x != nil {
		if x, ok := x.Mark.(*Embedded_Progress); ok {
			return x.Progress
		}
	}
	return 0
}

func (x *Embedded) GetNote() string {
	if x != nil {
		if x, ok := x.Mark.(*Embedded_Note); ok {
			return x.Note
		}
	}
	return ""
}

type isEmbedded_Mark interface {
	isEmbedded_Mark()
}

type Embedded_Progress struct {
	Progress int64 `protobuf:"varint,1,opt,name=progress,proto3,oneof"`
}

type Embedded_Note struct {
	Note string `protobuf:"bytes,2,opt,name=note,proto3,oneof"`
}

func (*Embedded_Progress) isEmbedded_Mark() {}

func (*Embedded_Note) isEmbedded_Mark() {}

// SimpleMessage represents a simple message sent to the Echo service.
type SimpleMessage struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Id represents the message identifier.
	Id  string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Num int64  `protobuf:"varint,2,opt,name=num,proto3" json:"num,omitempty"`
	// Types that are valid to be assigned to Code:
	//
	//	*SimpleMessage_LineNum
	//	*SimpleMessage_Lang
	Code   isSimpleMessage_Code `protobuf_oneof:"code"`
	Status *Embedded            `protobuf:"bytes,5,opt,name=status,proto3" json:"status,omitempty"`
	// Types that are valid to be assigned to Ext:
	//
	//	*SimpleMessage_En
	//	*SimpleMessage_No
	Ext           isSimpleMessage_Ext `protobuf_oneof:"ext"`
	ResourceId    string              `protobuf:"bytes,8,opt,name=resource_id,json=resourceId,proto3" json:"resource_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SimpleMessage) Reset() {
	*x = SimpleMessage{}
	mi := &file_test_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SimpleMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SimpleMessage) ProtoMessage() {}

func (x *SimpleMessage) ProtoReflect() protoreflect.Message {
	mi := &file_test_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SimpleMessage.ProtoReflect.Descriptor instead.
func (*SimpleMessage) Descriptor() ([]byte, []int) {
	return file_test_proto_rawDescGZIP(), []int{10}
}

func (x *SimpleMessage) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *SimpleMessage) GetNum() int64 {
	if x != nil {
		return x.Num
	}
	return 0
}

func (x *SimpleMessage) GetCode() isSimpleMessage_Code {
	if x != nil {
		return x.Code
	}
	return nil
}

func (x *SimpleMessage) GetLineNum() int64 {
	if x != nil {
		if x, ok := x.Code.(*SimpleMessage_LineNum); ok {
			return x.LineNum
		}
	}
	return 0
}

func (x *SimpleMessage) GetLang() string {
	if x != nil {
		if x, ok := x.Code.(*SimpleMessage_Lang); ok {
			return x.Lang
		}
	}
	return ""
}

func (x *SimpleMessage) GetStatus() *Embedded {
	if x != nil {
		return x.Status
	}
	return nil
}

func (x *SimpleMessage) GetExt() isSimpleMessage_Ext {
	if x != nil {
		return x.Ext
	}
	return nil
}

func (x *SimpleMessage) GetEn() int64 {
	if x != nil {
		if x, ok := x.Ext.(*SimpleMessage_En); ok {
			return x.En
		}
	}
	return 0
}

func (x *SimpleMessage) GetNo() *Embedded {
	if x != nil {
		if x, ok := x.Ext.(*SimpleMessage_No); ok {
			return x.No
		}
	}
	return nil
}

func (x *SimpleMessage) GetResourceId() string {
	if x != nil {
		return x.ResourceId
	}
	return ""
}

type isSimpleMessage_Code interface {
	isSimpleMessage_Code()
}

type SimpleMessage_LineNum struct {
	LineNum int64 `protobuf:"varint,3,opt,name=line_num,json=lineNum,proto3,oneof"`
}

type SimpleMessage_Lang struct {
	Lang string `protobuf:"bytes,4,opt,name=lang,proto3,oneof"`
}

func (*SimpleMessage_LineNum) isSimpleMessage_Code() {}

func (*SimpleMessage_Lang) isSimpleMessage_Code() {}

type isSimpleMessage_Ext interface {
	isSimpleMessage_Ext()
}

type SimpleMessage_En struct {
	En int64 `protobuf:"varint,6,opt,name=en,proto3,oneof"`
}

type SimpleMessage_No struct {
	No *Embedded `protobuf:"bytes,7,opt,name=no,proto3,oneof"`
}

func (*SimpleMessage_En) isSimpleMessage_Ext() {}

func (*SimpleMessage_No) isSimpleMessage_Ext() {}

// Nested is nested type.
type ABitOfEverything_Nested struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// name is nested field.
	Name   string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Amount uint32 `protobuf:"varint,2,opt,name=amount,proto3" json:"amount,omitempty"`
	// DeepEnum comment.
	Ok            ABitOfEverything_Nested_DeepEnum `protobuf:"varint,3,opt,name=ok,proto3,enum=grpc.gateway.internal.testpb.ABitOfEverything_Nested_DeepEnum" json:"ok,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ABitOfEverything_Nested) Reset() {
	*x = ABitOfEverything_Nested{}
	mi := &file_test_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ABitOfEverything_Nested) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ABitOfEverything_Nested) ProtoMessage() {}

func (x *ABitOfEverything_Nested) ProtoReflect() protoreflect.Message {
	mi := &file_test_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ABitOfEverything_Nested.ProtoReflect.Descriptor instead.
func (*ABitOfEverything_Nested) Descriptor() ([]byte, []int) {
	return file_test_proto_rawDescGZIP(), []int{0, 0}
}

func (x *ABitOfEverything_Nested) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ABitOfEverything_Nested) GetAmount() uint32 {
	if x != nil {
		return x.Amount
	}
	return 0
}

func (x *ABitOfEverything_Nested) GetOk() ABitOfEverything_Nested_DeepEnum {
	if x != nil {
		return x.Ok
	}
	return ABitOfEverything_Nested_FALSE
}

type ResponseBodyOut_Response struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Data          string                 `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ResponseBodyOut_Response) Reset() {
	*x = ResponseBodyOut_Response{}
	mi := &file_test_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResponseBodyOut_Response) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResponseBodyOut_Response) ProtoMessage() {}

func (x *ResponseBodyOut_Response) ProtoReflect() protoreflect.Message {
	mi := &file_test_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResponseBodyOut_Response.ProtoReflect.Descriptor instead.
func (*ResponseBodyOut_Response) Descriptor() ([]byte, []int) {
	return file_test_proto_rawDescGZIP(), []int{1, 0}
}

func (x *ResponseBodyOut_Response) GetData() string {
	if x != nil {
		return x.Data
	}
	return ""
}

type RepeatedResponseBodyOut_Response struct {
	state         protoimpl.MessageState                        `protogen:"open.v1"`
	Data          string                                        `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
	Type          RepeatedResponseBodyOut_Response_ResponseType `protobuf:"varint,3,opt,name=type,proto3,enum=grpc.gateway.internal.testpb.RepeatedResponseBodyOut_Response_ResponseType" json:"type,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RepeatedResponseBodyOut_Response) Reset() {
	*x = RepeatedResponseBodyOut_Response{}
	mi := &file_test_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RepeatedResponseBodyOut_Response) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RepeatedResponseBodyOut_Response) ProtoMessage() {}

func (x *RepeatedResponseBodyOut_Response) ProtoReflect() protoreflect.Message {
	mi := &file_test_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RepeatedResponseBodyOut_Response.ProtoReflect.Descriptor instead.
func (*RepeatedResponseBodyOut_Response) Descriptor() ([]byte, []int) {
	return file_test_proto_rawDescGZIP(), []int{2, 0}
}

func (x *RepeatedResponseBodyOut_Response) GetData() string {
	if x != nil {
		return x.Data
	}
	return ""
}

func (x *RepeatedResponseBodyOut_Response) GetType() RepeatedResponseBodyOut_Response_ResponseType {
	if x != nil {
		return x.Type
	}
	return RepeatedResponseBodyOut_Response_UNKNOWN
}

var File_test_proto protoreflect.FileDescriptor

const file_test_proto_rawDesc = "" +
	"\n" +
	"\n" +
	"test.proto\x12\x1cgrpc.gateway.internal.testpb\x1a\x19google/protobuf/any.proto\x1a\x1bgoogle/protobuf/empty.proto\x1a google/protobuf/field_mask.proto\x1a\x1fgoogle/protobuf/timestamp.proto\"\xbf\x14\n" +
	"\x10ABitOfEverything\x12Z\n" +
	"\rsingle_nested\x18\x19 \x01(\v25.grpc.gateway.internal.testpb.ABitOfEverything.NestedR\fsingleNested\x12\x12\n" +
	"\x04uuid\x18\x01 \x01(\tR\x04uuid\x12M\n" +
	"\x06nested\x18\x02 \x03(\v25.grpc.gateway.internal.testpb.ABitOfEverything.NestedR\x06nested\x12\x1f\n" +
	"\vfloat_value\x18\x03 \x01(\x02R\n" +
	"floatValue\x12!\n" +
	"\fdouble_value\x18\x04 \x01(\x01R\vdoubleValue\x12\x1f\n" +
	"\vint64_value\x18\x05 \x01(\x03R\n" +
	"int64Value\x12!\n" +
	"\fuint64_value\x18\x06 \x01(\x04R\vuint64Value\x12\x1f\n" +
	"\vint32_value\x18\a \x01(\x05R\n" +
	"int32Value\x12#\n" +
	"\rfixed64_value\x18\b \x01(\x06R\ffixed64Value\x12#\n" +
	"\rfixed32_value\x18\t \x01(\aR\ffixed32Value\x12\x1d\n" +
	"\n" +
	"bool_value\x18\n" +
	" \x01(\bR\tboolValue\x12!\n" +
	"\fstring_value\x18\v \x01(\tR\vstringValue\x12\x1f\n" +
	"\vbytes_value\x18\x1d \x01(\fR\n" +
	"bytesValue\x12!\n" +
	"\fuint32_value\x18\r \x01(\rR\vuint32Value\x12H\n" +
	"\n" +
	"enum_value\x18\x0e \x01(\x0e2).grpc.gateway.internal.testpb.NumericEnumR\tenumValue\x12%\n" +
	"\x0esfixed32_value\x18\x0f \x01(\x0fR\rsfixed32Value\x12%\n" +
	"\x0esfixed64_value\x18\x10 \x01(\x10R\rsfixed64Value\x12!\n" +
	"\fsint32_value\x18\x11 \x01(\x11R\vsint32Value\x12!\n" +
	"\fsint64_value\x18\x12 \x01(\x12R\vsint64Value\x122\n" +
	"\x15repeated_string_value\x18\x13 \x03(\tR\x13repeatedStringValue\x129\n" +
	"\voneof_empty\x18\x14 \x01(\v2\x16.google.protobuf.EmptyH\x00R\n" +
	"oneofEmpty\x12#\n" +
	"\foneof_string\x18\x15 \x01(\tH\x00R\voneofString\x12Y\n" +
	"\tmap_value\x18\x16 \x03(\v2<.grpc.gateway.internal.testpb.ABitOfEverything.MapValueEntryR\bmapValue\x12u\n" +
	"\x13mapped_string_value\x18\x17 \x03(\v2E.grpc.gateway.internal.testpb.ABitOfEverything.MappedStringValueEntryR\x11mappedStringValue\x12u\n" +
	"\x13mapped_nested_value\x18\x18 \x03(\v2E.grpc.gateway.internal.testpb.ABitOfEverything.MappedNestedValueEntryR\x11mappedNestedValue\x12:\n" +
	"\x18nonConventionalNameValue\x18\x1a \x01(\tR\x18nonConventionalNameValue\x12C\n" +
	"\x0ftimestamp_value\x18\x1b \x01(\v2\x1a.google.protobuf.TimestampR\x0etimestampValue\x12Y\n" +
	"\x13repeated_enum_value\x18\x1c \x03(\x0e2).grpc.gateway.internal.testpb.NumericEnumR\x11repeatedEnumValue\x12c\n" +
	"\x18repeated_enum_annotation\x18  \x03(\x0e2).grpc.gateway.internal.testpb.NumericEnumR\x16repeatedEnumAnnotation\x12]\n" +
	"\x15enum_value_annotation\x18! \x01(\x0e2).grpc.gateway.internal.testpb.NumericEnumR\x13enumValueAnnotation\x12<\n" +
	"\x1arepeated_string_annotation\x18\" \x03(\tR\x18repeatedStringAnnotation\x12s\n" +
	"\x1arepeated_nested_annotation\x18# \x03(\v25.grpc.gateway.internal.testpb.ABitOfEverything.NestedR\x18repeatedNestedAnnotation\x12b\n" +
	"\x11nested_annotation\x18$ \x01(\v25.grpc.gateway.internal.testpb.ABitOfEverything.NestedR\x10nestedAnnotation\x12.\n" +
	"\x13int64_override_type\x18% \x01(\x03R\x11int64OverrideType\x12.\n" +
	"\aanytype\x18& \x01(\v2\x14.google.protobuf.AnyR\aanytype\x12?\n" +
	"\x10repeated_anytype\x18' \x03(\v2\x14.google.protobuf.AnyR\x0frepeatedAnytype\x1a\xa5\x01\n" +
	"\x06Nested\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x16\n" +
	"\x06amount\x18\x02 \x01(\rR\x06amount\x12N\n" +
	"\x02ok\x18\x03 \x01(\x0e2>.grpc.gateway.internal.testpb.ABitOfEverything.Nested.DeepEnumR\x02ok\"\x1f\n" +
	"\bDeepEnum\x12\t\n" +
	"\x05FALSE\x10\x00\x12\b\n" +
	"\x04TRUE\x10\x01\x1af\n" +
	"\rMapValueEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12?\n" +
	"\x05value\x18\x02 \x01(\x0e2).grpc.gateway.internal.testpb.NumericEnumR\x05value:\x028\x01\x1aD\n" +
	"\x16MappedStringValueEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\x1a{\n" +
	"\x16MappedNestedValueEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12K\n" +
	"\x05value\x18\x02 \x01(\v25.grpc.gateway.internal.testpb.ABitOfEverything.NestedR\x05value:\x028\x01B\r\n" +
	"\voneof_value\"\x85\x01\n" +
	"\x0fResponseBodyOut\x12R\n" +
	"\bresponse\x18\x02 \x01(\v26.grpc.gateway.internal.testpb.ResponseBodyOut.ResponseR\bresponse\x1a\x1e\n" +
	"\bResponse\x12\x12\n" +
	"\x04data\x18\x01 \x01(\tR\x04data\"\xa2\x02\n" +
	"\x17RepeatedResponseBodyOut\x12Z\n" +
	"\bresponse\x18\x02 \x03(\v2>.grpc.gateway.internal.testpb.RepeatedResponseBodyOut.ResponseR\bresponse\x1a\xaa\x01\n" +
	"\bResponse\x12\x12\n" +
	"\x04data\x18\x01 \x01(\tR\x04data\x12_\n" +
	"\x04type\x18\x03 \x01(\x0e2K.grpc.gateway.internal.testpb.RepeatedResponseBodyOut.Response.ResponseTypeR\x04type\")\n" +
	"\fResponseType\x12\v\n" +
	"\aUNKNOWN\x10\x00\x12\x05\n" +
	"\x01A\x10\x01\x12\x05\n" +
	"\x01B\x10\x02\"\xab\x01\n" +
	"\rUpdateMessage\x12;\n" +
	"\vupdate_mask\x18\x01 \x01(\v2\x1a.google.protobuf.FieldMaskR\n" +
	"updateMask\x12]\n" +
	"\x13a_bit_of_everything\x18\x02 \x01(\v2..grpc.gateway.internal.testpb.ABitOfEverythingR\x10aBitOfEverything\"H\n" +
	"\vNestedOuter\x129\n" +
	"\x03one\x18\x01 \x01(\v2'.grpc.gateway.internal.testpb.NestedOneR\x03one\"F\n" +
	"\tNestedOne\x129\n" +
	"\x03two\x18\x01 \x01(\v2'.grpc.gateway.internal.testpb.NestedTwoR\x03two\"L\n" +
	"\tNestedTwo\x12?\n" +
	"\x05three\x18\x01 \x01(\v2).grpc.gateway.internal.testpb.NestedThreeR\x05three\")\n" +
	"\vNestedThree\x12\f\n" +
	"\x01a\x18\x01 \x01(\bR\x01a\x12\f\n" +
	"\x01b\x18\x02 \x01(\bR\x01b\"\x95\x01\n" +
	"\x13UpdateNestedRequest\x12A\n" +
	"\x06nested\x18\x01 \x01(\v2).grpc.gateway.internal.testpb.NestedOuterR\x06nested\x12;\n" +
	"\vupdate_mask\x18\x02 \x01(\v2\x1a.google.protobuf.FieldMaskR\n" +
	"updateMask\"F\n" +
	"\bEmbedded\x12\x1c\n" +
	"\bprogress\x18\x01 \x01(\x03H\x00R\bprogress\x12\x14\n" +
	"\x04note\x18\x02 \x01(\tH\x00R\x04noteB\x06\n" +
	"\x04mark\"\xa0\x02\n" +
	"\rSimpleMessage\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x10\n" +
	"\x03num\x18\x02 \x01(\x03R\x03num\x12\x1b\n" +
	"\bline_num\x18\x03 \x01(\x03H\x00R\alineNum\x12\x14\n" +
	"\x04lang\x18\x04 \x01(\tH\x00R\x04lang\x12>\n" +
	"\x06status\x18\x05 \x01(\v2&.grpc.gateway.internal.testpb.EmbeddedR\x06status\x12\x10\n" +
	"\x02en\x18\x06 \x01(\x03H\x01R\x02en\x128\n" +
	"\x02no\x18\a \x01(\v2&.grpc.gateway.internal.testpb.EmbeddedH\x01R\x02no\x12\x1f\n" +
	"\vresource_id\x18\b \x01(\tR\n" +
	"resourceIdB\x06\n" +
	"\x04codeB\x05\n" +
	"\x03ext* \n" +
	"\vNumericEnum\x12\b\n" +
	"\x04ZERO\x10\x00\x12\a\n" +
	"\x03ONE\x10\x01B5Z3github.com/meshapi/grpc-api-gateway/internal/testpbb\x06proto3"

var (
	file_test_proto_rawDescOnce sync.Once
	file_test_proto_rawDescData []byte
)

func file_test_proto_rawDescGZIP() []byte {
	file_test_proto_rawDescOnce.Do(func() {
		file_test_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_test_proto_rawDesc), len(file_test_proto_rawDesc)))
	})
	return file_test_proto_rawDescData
}

var file_test_proto_enumTypes = make([]protoimpl.EnumInfo, 3)
var file_test_proto_msgTypes = make([]protoimpl.MessageInfo, 17)
var file_test_proto_goTypes = []any{
	(NumericEnum)(0),                                   // 0: grpc.gateway.internal.testpb.NumericEnum
	(ABitOfEverything_Nested_DeepEnum)(0),              // 1: grpc.gateway.internal.testpb.ABitOfEverything.Nested.DeepEnum
	(RepeatedResponseBodyOut_Response_ResponseType)(0), // 2: grpc.gateway.internal.testpb.RepeatedResponseBodyOut.Response.ResponseType
	(*ABitOfEverything)(nil),                           // 3: grpc.gateway.internal.testpb.ABitOfEverything
	(*ResponseBodyOut)(nil),                            // 4: grpc.gateway.internal.testpb.ResponseBodyOut
	(*RepeatedResponseBodyOut)(nil),                    // 5: grpc.gateway.internal.testpb.RepeatedResponseBodyOut
	(*UpdateMessage)(nil),                              // 6: grpc.gateway.internal.testpb.UpdateMessage
	(*NestedOuter)(nil),                                // 7: grpc.gateway.internal.testpb.NestedOuter
	(*NestedOne)(nil),                                  // 8: grpc.gateway.internal.testpb.NestedOne
	(*NestedTwo)(nil),                                  // 9: grpc.gateway.internal.testpb.NestedTwo
	(*NestedThree)(nil),                                // 10: grpc.gateway.internal.testpb.NestedThree
	(*UpdateNestedRequest)(nil),                        // 11: grpc.gateway.internal.testpb.UpdateNestedRequest
	(*Embedded)(nil),                                   // 12: grpc.gateway.internal.testpb.Embedded
	(*SimpleMessage)(nil),                              // 13: grpc.gateway.internal.testpb.SimpleMessage
	(*ABitOfEverything_Nested)(nil),                    // 14: grpc.gateway.internal.testpb.ABitOfEverything.Nested
	nil,                                                // 15: grpc.gateway.internal.testpb.ABitOfEverything.MapValueEntry
	nil,                                                // 16: grpc.gateway.internal.testpb.ABitOfEverything.MappedStringValueEntry
	nil,                                                // 17: grpc.gateway.internal.testpb.ABitOfEverything.MappedNestedValueEntry
	(*ResponseBodyOut_Response)(nil),                   // 18: grpc.gateway.internal.testpb.ResponseBodyOut.Response
	(*RepeatedResponseBodyOut_Response)(nil),           // 19: grpc.gateway.internal.testpb.RepeatedResponseBodyOut.Response
	(*emptypb.Empty)(nil),                              // 20: google.protobuf.Empty
	(*timestamppb.Timestamp)(nil),                      // 21: google.protobuf.Timestamp
	(*anypb.Any)(nil),                                  // 22: google.protobuf.Any
	(*fieldmaskpb.FieldMask)(nil),                      // 23: google.protobuf.FieldMask
}
var file_test_proto_depIdxs = []int32{
	14, // 0: grpc.gateway.internal.testpb.ABitOfEverything.single_nested:type_name -> grpc.gateway.internal.testpb.ABitOfEverything.Nested
	14, // 1: grpc.gateway.internal.testpb.ABitOfEverything.nested:type_name -> grpc.gateway.internal.testpb.ABitOfEverything.Nested
	0,  // 2: grpc.gateway.internal.testpb.ABitOfEverything.enum_value:type_name -> grpc.gateway.internal.testpb.NumericEnum
	20, // 3: grpc.gateway.internal.testpb.ABitOfEverything.oneof_empty:type_name -> google.protobuf.Empty
	15, // 4: grpc.gateway.internal.testpb.ABitOfEverything.map_value:type_name -> grpc.gateway.internal.testpb.ABitOfEverything.MapValueEntry
	16, // 5: grpc.gateway.internal.testpb.ABitOfEverything.mapped_string_value:type_name -> grpc.gateway.internal.testpb.ABitOfEverything.MappedStringValueEntry
	17, // 6: grpc.gateway.internal.testpb.ABitOfEverything.mapped_nested_value:type_name -> grpc.gateway.internal.testpb.ABitOfEverything.MappedNestedValueEntry
	21, // 7: grpc.gateway.internal.testpb.ABitOfEverything.timestamp_value:type_name -> google.protobuf.Timestamp
	0,  // 8: grpc.gateway.internal.testpb.ABitOfEverything.repeated_enum_value:type_name -> grpc.gateway.internal.testpb.NumericEnum
	0,  // 9: grpc.gateway.internal.testpb.ABitOfEverything.repeated_enum_annotation:type_name -> grpc.gateway.internal.testpb.NumericEnum
	0,  // 10: grpc.gateway.internal.testpb.ABitOfEverything.enum_value_annotation:type_name -> grpc.gateway.internal.testpb.NumericEnum
	14, // 11: grpc.gateway.internal.testpb.ABitOfEverything.repeated_nested_annotation:type_name -> grpc.gateway.internal.testpb.ABitOfEverything.Nested
	14, // 12: grpc.gateway.internal.testpb.ABitOfEverything.nested_annotation:type_name -> grpc.gateway.internal.testpb.ABitOfEverything.Nested
	22, // 13: grpc.gateway.internal.testpb.ABitOfEverything.anytype:type_name -> google.protobuf.Any
	22, // 14: grpc.gateway.internal.testpb.ABitOfEverything.repeated_anytype:type_name -> google.protobuf.Any
	18, // 15: grpc.gateway.internal.testpb.ResponseBodyOut.response:type_name -> grpc.gateway.internal.testpb.ResponseBodyOut.Response
	19, // 16: grpc.gateway.internal.testpb.RepeatedResponseBodyOut.response:type_name -> grpc.gateway.internal.testpb.RepeatedResponseBodyOut.Response
	23, // 17: grpc.gateway.internal.testpb.UpdateMessage.update_mask:type_name -> google.protobuf.FieldMask
	3,  // 18: grpc.gateway.internal.testpb.UpdateMessage.a_bit_of_everything:type_name -> grpc.gateway.internal.testpb.ABitOfEverything
	8,  // 19: grpc.gateway.internal.testpb.NestedOuter.one:type_name -> grpc.gateway.internal.testpb.NestedOne
	9,  // 20: grpc.gateway.internal.testpb.NestedOne.two:type_name -> grpc.gateway.internal.testpb.NestedTwo
	10, // 21: grpc.gateway.internal.testpb.NestedTwo.three:type_name -> grpc.gateway.internal.testpb.NestedThree
	7,  // 22: grpc.gateway.internal.testpb.UpdateNestedRequest.nested:type_name -> grpc.gateway.internal.testpb.NestedOuter
	23, // 23: grpc.gateway.internal.testpb.UpdateNestedRequest.update_mask:type_name -> google.protobuf.FieldMask
	12, // 24: grpc.gateway.internal.testpb.SimpleMessage.status:type_name -> grpc.gateway.internal.testpb.Embedded
	12, // 25: grpc.gateway.internal.testpb.SimpleMessage.no:type_name -> grpc.gateway.internal.testpb.Embedded
	1,  // 26: grpc.gateway.internal.testpb.ABitOfEverything.Nested.ok:type_name -> grpc.gateway.internal.testpb.ABitOfEverything.Nested.DeepEnum
	0,  // 27: grpc.gateway.internal.testpb.ABitOfEverything.MapValueEntry.value:type_name -> grpc.gateway.internal.testpb.NumericEnum
	14, // 28: grpc.gateway.internal.testpb.ABitOfEverything.MappedNestedValueEntry.value:type_name -> grpc.gateway.internal.testpb.ABitOfEverything.Nested
	2,  // 29: grpc.gateway.internal.testpb.RepeatedResponseBodyOut.Response.type:type_name -> grpc.gateway.internal.testpb.RepeatedResponseBodyOut.Response.ResponseType
	30, // [30:30] is the sub-list for method output_type
	30, // [30:30] is the sub-list for method input_type
	30, // [30:30] is the sub-list for extension type_name
	30, // [30:30] is the sub-list for extension extendee
	0,  // [0:30] is the sub-list for field type_name
}

func init() { file_test_proto_init() }
func file_test_proto_init() {
	if File_test_proto != nil {
		return
	}
	file_test_proto_msgTypes[0].OneofWrappers = []any{
		(*ABitOfEverything_OneofEmpty)(nil),
		(*ABitOfEverything_OneofString)(nil),
	}
	file_test_proto_msgTypes[9].OneofWrappers = []any{
		(*Embedded_Progress)(nil),
		(*Embedded_Note)(nil),
	}
	file_test_proto_msgTypes[10].OneofWrappers = []any{
		(*SimpleMessage_LineNum)(nil),
		(*SimpleMessage_Lang)(nil),
		(*SimpleMessage_En)(nil),
		(*SimpleMessage_No)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_test_proto_rawDesc), len(file_test_proto_rawDesc)),
			NumEnums:      3,
			NumMessages:   17,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_test_proto_goTypes,
		DependencyIndexes: file_test_proto_depIdxs,
		EnumInfos:         file_test_proto_enumTypes,
		MessageInfos:      file_test_proto_msgTypes,
	}.Build()
	File_test_proto = out.File
	file_test_proto_goTypes = nil
	file_test_proto_depIdxs = nil
}
