// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.9
// 	protoc        (unknown)
// source: gopencloud/gateway/annotations.proto

package api

import (
	openapi "github.com/gopencloud/grpc-api-gateway/api/openapi"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	descriptorpb "google.golang.org/protobuf/types/descriptorpb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ProtoEndpointBinding struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Pattern:
	//
	//	*ProtoEndpointBinding_Get
	//	*ProtoEndpointBinding_Put
	//	*ProtoEndpointBinding_Post
	//	*ProtoEndpointBinding_Delete
	//	*ProtoEndpointBinding_Patch
	//	*ProtoEndpointBinding_Custom
	Pattern                    isProtoEndpointBinding_Pattern `protobuf_oneof:"pattern"`
	Body                       *string                        `protobuf:"bytes,8,opt,name=body" json:"body,omitempty"`
	QueryParams                []*QueryParameterBinding       `protobuf:"bytes,9,rep,name=query_params,json=queryParams" json:"query_params,omitempty"`
	AdditionalBindings         []*AdditionalEndpointBinding   `protobuf:"bytes,10,rep,name=additional_bindings,json=additionalBindings" json:"additional_bindings,omitempty"`
	DisableQueryParamDiscovery *bool                          `protobuf:"varint,11,opt,name=disable_query_param_discovery,json=disableQueryParamDiscovery" json:"disable_query_param_discovery,omitempty"`
	Stream                     *StreamConfig                  `protobuf:"bytes,12,opt,name=stream" json:"stream,omitempty"`
	// aliases are additional routes for this endpoint binding.
	//
	// This field translates to additional_bindings, inheriting all values from
	// endpoint binding. Consider this a syntax sugar for additional_bindings. If
	// additional binding with same route and method exists, alias will not work.
	Aliases       []string `protobuf:"bytes,13,rep,name=aliases" json:"aliases,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProtoEndpointBinding) Reset() {
	*x = ProtoEndpointBinding{}
	mi := &file_gopencloud_gateway_annotations_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProtoEndpointBinding) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProtoEndpointBinding) ProtoMessage() {}

func (x *ProtoEndpointBinding) ProtoReflect() protoreflect.Message {
	mi := &file_gopencloud_gateway_annotations_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProtoEndpointBinding.ProtoReflect.Descriptor instead.
func (*ProtoEndpointBinding) Descriptor() ([]byte, []int) {
	return file_gopencloud_gateway_annotations_proto_rawDescGZIP(), []int{0}
}

func (x *ProtoEndpointBinding) GetPattern() isProtoEndpointBinding_Pattern {
	if x != nil {
		return x.Pattern
	}
	return nil
}

func (x *ProtoEndpointBinding) GetGet() string {
	if x != nil {
		if x, ok := x.Pattern.(*ProtoEndpointBinding_Get); ok {
			return x.Get
		}
	}
	return ""
}

func (x *ProtoEndpointBinding) GetPut() string {
	if x != nil {
		if x, ok := x.Pattern.(*ProtoEndpointBinding_Put); ok {
			return x.Put
		}
	}
	return ""
}

func (x *ProtoEndpointBinding) GetPost() string {
	if x != nil {
		if x, ok := x.Pattern.(*ProtoEndpointBinding_Post); ok {
			return x.Post
		}
	}
	return ""
}

func (x *ProtoEndpointBinding) GetDelete() string {
	if x != nil {
		if x, ok := x.Pattern.(*ProtoEndpointBinding_Delete); ok {
			return x.Delete
		}
	}
	return ""
}

func (x *ProtoEndpointBinding) GetPatch() string {
	if x != nil {
		if x, ok := x.Pattern.(*ProtoEndpointBinding_Patch); ok {
			return x.Patch
		}
	}
	return ""
}

func (x *ProtoEndpointBinding) GetCustom() *CustomPattern {
	if x != nil {
		if x, ok := x.Pattern.(*ProtoEndpointBinding_Custom); ok {
			return x.Custom
		}
	}
	return nil
}

func (x *ProtoEndpointBinding) GetBody() string {
	if x != nil && x.Body != nil {
		return *x.Body
	}
	return ""
}

func (x *ProtoEndpointBinding) GetQueryParams() []*QueryParameterBinding {
	if x != nil {
		return x.QueryParams
	}
	return nil
}

func (x *ProtoEndpointBinding) GetAdditionalBindings() []*AdditionalEndpointBinding {
	if x != nil {
		return x.AdditionalBindings
	}
	return nil
}

func (x *ProtoEndpointBinding) GetDisableQueryParamDiscovery() bool {
	if x != nil && x.DisableQueryParamDiscovery != nil {
		return *x.DisableQueryParamDiscovery
	}
	return false
}

func (x *ProtoEndpointBinding) GetStream() *StreamConfig {
	if x != nil {
		return x.Stream
	}
	return nil
}

func (x *ProtoEndpointBinding) GetAliases() []string {
	if x != nil {
		return x.Aliases
	}
	return nil
}

type isProtoEndpointBinding_Pattern interface {
	isProtoEndpointBinding_Pattern()
}

type ProtoEndpointBinding_Get struct {
	Get string `protobuf:"bytes,2,opt,name=get,oneof"`
}

type ProtoEndpointBinding_Put struct {
	Put string `protobuf:"bytes,3,opt,name=put,oneof"`
}

type ProtoEndpointBinding_Post struct {
	Post string `protobuf:"bytes,4,opt,name=post,oneof"`
}

type ProtoEndpointBinding_Delete struct {
	Delete string `protobuf:"bytes,5,opt,name=delete,oneof"`
}

type ProtoEndpointBinding_Patch struct {
	Patch string `protobuf:"bytes,6,opt,name=patch,oneof"`
}

type ProtoEndpointBinding_Custom struct {
	// custom can be used for custom HTTP methods.
	Custom *CustomPattern `protobuf:"bytes,7,opt,name=custom,oneof"`
}

func (*ProtoEndpointBinding_Get) isProtoEndpointBinding_Pattern() {}

func (*ProtoEndpointBinding_Put) isProtoEndpointBinding_Pattern() {}

func (*ProtoEndpointBinding_Post) isProtoEndpointBinding_Pattern() {}

func (*ProtoEndpointBinding_Delete) isProtoEndpointBinding_Pattern() {}

func (*ProtoEndpointBinding_Patch) isProtoEndpointBinding_Pattern() {}

func (*ProtoEndpointBinding_Custom) isProtoEndpointBinding_Pattern() {}

var file_gopencloud_gateway_annotations_proto_extTypes = []protoimpl.ExtensionInfo{
	{
		ExtendedType:  (*descriptorpb.FileOptions)(nil),
		ExtensionType: (*openapi.Document)(nil),
		Field:         1191,
		Name:          "gopencloud.gateway.openapi_doc",
		Tag:           "bytes,1191,opt,name=openapi_doc",
		Filename:      "gopencloud/gateway/annotations.proto",
	},
	{
		ExtendedType:  (*descriptorpb.ServiceOptions)(nil),
		ExtensionType: (*openapi.Document)(nil),
		Field:         1191,
		Name:          "gopencloud.gateway.openapi_service_doc",
		Tag:           "bytes,1191,opt,name=openapi_service_doc",
		Filename:      "gopencloud/gateway/annotations.proto",
	},
	{
		ExtendedType:  (*descriptorpb.MethodOptions)(nil),
		ExtensionType: (*ProtoEndpointBinding)(nil),
		Field:         1190,
		Name:          "gopencloud.gateway.http",
		Tag:           "bytes,1190,opt,name=http",
		Filename:      "gopencloud/gateway/annotations.proto",
	},
	{
		ExtendedType:  (*descriptorpb.MethodOptions)(nil),
		ExtensionType: (*openapi.Operation)(nil),
		Field:         1191,
		Name:          "gopencloud.gateway.openapi_operation",
		Tag:           "bytes,1191,opt,name=openapi_operation",
		Filename:      "gopencloud/gateway/annotations.proto",
	},
	{
		ExtendedType:  (*descriptorpb.MessageOptions)(nil),
		ExtensionType: (*openapi.Schema)(nil),
		Field:         1191,
		Name:          "gopencloud.gateway.openapi_schema",
		Tag:           "bytes,1191,opt,name=openapi_schema",
		Filename:      "gopencloud/gateway/annotations.proto",
	},
	{
		ExtendedType:  (*descriptorpb.EnumOptions)(nil),
		ExtensionType: (*openapi.Schema)(nil),
		Field:         1191,
		Name:          "gopencloud.gateway.openapi_enum",
		Tag:           "bytes,1191,opt,name=openapi_enum",
		Filename:      "gopencloud/gateway/annotations.proto",
	},
	{
		ExtendedType:  (*descriptorpb.FieldOptions)(nil),
		ExtensionType: (*openapi.Schema)(nil),
		Field:         1191,
		Name:          "gopencloud.gateway.openapi_field",
		Tag:           "bytes,1191,opt,name=openapi_field",
		Filename:      "gopencloud/gateway/annotations.proto",
	},
}

// Extension fields to descriptorpb.FileOptions.
var (
	// openapi_doc holds OpenAPI file options.
	//
	// optional gopencloud.gateway.openapi.Document openapi_doc = 1191;
	E_OpenapiDoc = &file_gopencloud_gateway_annotations_proto_extTypes[0]
)

// Extension fields to descriptorpb.ServiceOptions.
var (
	// openapi_service_doc holds OpenAPI file options.
	//
	// optional gopencloud.gateway.openapi.Document openapi_service_doc = 1191;
	E_OpenapiServiceDoc = &file_gopencloud_gateway_annotations_proto_extTypes[1]
)

// Extension fields to descriptorpb.MethodOptions.
var (
	// http holds HTTP endpoint binding configs.
	//
	// ID assigned by protobuf-global-extension-registry@google.com for
	// gRPC-Gateway project.
	//
	// optional gopencloud.gateway.ProtoEndpointBinding http = 1190;
	E_Http = &file_gopencloud_gateway_annotations_proto_extTypes[2]
	// openapi_operation holds OpenAPI method/operation options.
	//
	// optional gopencloud.gateway.openapi.Operation openapi_operation = 1191;
	E_OpenapiOperation = &file_gopencloud_gateway_annotations_proto_extTypes[3]
)

// Extension fields to descriptorpb.MessageOptions.
var (
	// optional gopencloud.gateway.openapi.Schema openapi_schema = 1191;
	E_OpenapiSchema = &file_gopencloud_gateway_annotations_proto_extTypes[4]
)

// Extension fields to descriptorpb.EnumOptions.
var (
	// optional gopencloud.gateway.openapi.Schema openapi_enum = 1191;
	E_OpenapiEnum = &file_gopencloud_gateway_annotations_proto_extTypes[5]
)

// Extension fields to descriptorpb.FieldOptions.
var (
	// optional gopencloud.gateway.openapi.Schema openapi_field = 1191;
	E_OpenapiField = &file_gopencloud_gateway_annotations_proto_extTypes[6]
)

var File_gopencloud_gateway_annotations_proto protoreflect.FileDescriptor

const file_gopencloud_gateway_annotations_proto_rawDesc = "" +
	"\n" +
	"$gopencloud/gateway/annotations.proto\x12\x12gopencloud.gateway\x1a google/protobuf/descriptor.proto\x1a gopencloud/gateway/gateway.proto\x1a(gopencloud/gateway/openapi/openapi.proto\"\xa7\x04\n" +
	"\x14ProtoEndpointBinding\x12\x12\n" +
	"\x03get\x18\x02 \x01(\tH\x00R\x03get\x12\x12\n" +
	"\x03put\x18\x03 \x01(\tH\x00R\x03put\x12\x14\n" +
	"\x04post\x18\x04 \x01(\tH\x00R\x04post\x12\x18\n" +
	"\x06delete\x18\x05 \x01(\tH\x00R\x06delete\x12\x16\n" +
	"\x05patch\x18\x06 \x01(\tH\x00R\x05patch\x12;\n" +
	"\x06custom\x18\a \x01(\v2!.gopencloud.gateway.CustomPatternH\x00R\x06custom\x12\x12\n" +
	"\x04body\x18\b \x01(\tR\x04body\x12L\n" +
	"\fquery_params\x18\t \x03(\v2).gopencloud.gateway.QueryParameterBindingR\vqueryParams\x12^\n" +
	"\x13additional_bindings\x18\n" +
	" \x03(\v2-.gopencloud.gateway.AdditionalEndpointBindingR\x12additionalBindings\x12A\n" +
	"\x1ddisable_query_param_discovery\x18\v \x01(\bR\x1adisableQueryParamDiscovery\x128\n" +
	"\x06stream\x18\f \x01(\v2 .gopencloud.gateway.StreamConfigR\x06stream\x12\x18\n" +
	"\aaliases\x18\r \x03(\tR\aaliasesB\t\n" +
	"\apattern:d\n" +
	"\vopenapi_doc\x12\x1c.google.protobuf.FileOptions\x18\xa7\t \x01(\v2$.gopencloud.gateway.openapi.DocumentR\n" +
	"openapiDoc:v\n" +
	"\x13openapi_service_doc\x12\x1f.google.protobuf.ServiceOptions\x18\xa7\t \x01(\v2$.gopencloud.gateway.openapi.DocumentR\x11openapiServiceDoc:]\n" +
	"\x04http\x12\x1e.google.protobuf.MethodOptions\x18\xa6\t \x01(\v2(.gopencloud.gateway.ProtoEndpointBindingR\x04http:s\n" +
	"\x11openapi_operation\x12\x1e.google.protobuf.MethodOptions\x18\xa7\t \x01(\v2%.gopencloud.gateway.openapi.OperationR\x10openapiOperation:k\n" +
	"\x0eopenapi_schema\x12\x1f.google.protobuf.MessageOptions\x18\xa7\t \x01(\v2\".gopencloud.gateway.openapi.SchemaR\ropenapiSchema:d\n" +
	"\fopenapi_enum\x12\x1c.google.protobuf.EnumOptions\x18\xa7\t \x01(\v2\".gopencloud.gateway.openapi.SchemaR\vopenapiEnum:g\n" +
	"\ropenapi_field\x12\x1d.google.protobuf.FieldOptions\x18\xa7\t \x01(\v2\".gopencloud.gateway.openapi.SchemaR\fopenapiFieldB,Z*github.com/gopencloud/grpc-api-gateway/apib\beditionsp\xe8\a"

var (
	file_gopencloud_gateway_annotations_proto_rawDescOnce sync.Once
	file_gopencloud_gateway_annotations_proto_rawDescData []byte
)

func file_gopencloud_gateway_annotations_proto_rawDescGZIP() []byte {
	file_gopencloud_gateway_annotations_proto_rawDescOnce.Do(func() {
		file_gopencloud_gateway_annotations_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_gopencloud_gateway_annotations_proto_rawDesc), len(file_gopencloud_gateway_annotations_proto_rawDesc)))
	})
	return file_gopencloud_gateway_annotations_proto_rawDescData
}

var file_gopencloud_gateway_annotations_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_gopencloud_gateway_annotations_proto_goTypes = []any{
	(*ProtoEndpointBinding)(nil),        // 0: gopencloud.gateway.ProtoEndpointBinding
	(*CustomPattern)(nil),               // 1: gopencloud.gateway.CustomPattern
	(*QueryParameterBinding)(nil),       // 2: gopencloud.gateway.QueryParameterBinding
	(*AdditionalEndpointBinding)(nil),   // 3: gopencloud.gateway.AdditionalEndpointBinding
	(*StreamConfig)(nil),                // 4: gopencloud.gateway.StreamConfig
	(*descriptorpb.FileOptions)(nil),    // 5: google.protobuf.FileOptions
	(*descriptorpb.ServiceOptions)(nil), // 6: google.protobuf.ServiceOptions
	(*descriptorpb.MethodOptions)(nil),  // 7: google.protobuf.MethodOptions
	(*descriptorpb.MessageOptions)(nil), // 8: google.protobuf.MessageOptions
	(*descriptorpb.EnumOptions)(nil),    // 9: google.protobuf.EnumOptions
	(*descriptorpb.FieldOptions)(nil),   // 10: google.protobuf.FieldOptions
	(*openapi.Document)(nil),            // 11: gopencloud.gateway.openapi.Document
	(*openapi.Operation)(nil),           // 12: gopencloud.gateway.openapi.Operation
	(*openapi.Schema)(nil),              // 13: gopencloud.gateway.openapi.Schema
}
var file_gopencloud_gateway_annotations_proto_depIdxs = []int32{
	1,  // 0: gopencloud.gateway.ProtoEndpointBinding.custom:type_name -> gopencloud.gateway.CustomPattern
	2,  // 1: gopencloud.gateway.ProtoEndpointBinding.query_params:type_name -> gopencloud.gateway.QueryParameterBinding
	3,  // 2: gopencloud.gateway.ProtoEndpointBinding.additional_bindings:type_name -> gopencloud.gateway.AdditionalEndpointBinding
	4,  // 3: gopencloud.gateway.ProtoEndpointBinding.stream:type_name -> gopencloud.gateway.StreamConfig
	5,  // 4: gopencloud.gateway.openapi_doc:extendee -> google.protobuf.FileOptions
	6,  // 5: gopencloud.gateway.openapi_service_doc:extendee -> google.protobuf.ServiceOptions
	7,  // 6: gopencloud.gateway.http:extendee -> google.protobuf.MethodOptions
	7,  // 7: gopencloud.gateway.openapi_operation:extendee -> google.protobuf.MethodOptions
	8,  // 8: gopencloud.gateway.openapi_schema:extendee -> google.protobuf.MessageOptions
	9,  // 9: gopencloud.gateway.openapi_enum:extendee -> google.protobuf.EnumOptions
	10, // 10: gopencloud.gateway.openapi_field:extendee -> google.protobuf.FieldOptions
	11, // 11: gopencloud.gateway.openapi_doc:type_name -> gopencloud.gateway.openapi.Document
	11, // 12: gopencloud.gateway.openapi_service_doc:type_name -> gopencloud.gateway.openapi.Document
	0,  // 13: gopencloud.gateway.http:type_name -> gopencloud.gateway.ProtoEndpointBinding
	12, // 14: gopencloud.gateway.openapi_operation:type_name -> gopencloud.gateway.openapi.Operation
	13, // 15: gopencloud.gateway.openapi_schema:type_name -> gopencloud.gateway.openapi.Schema
	13, // 16: gopencloud.gateway.openapi_enum:type_name -> gopencloud.gateway.openapi.Schema
	13, // 17: gopencloud.gateway.openapi_field:type_name -> gopencloud.gateway.openapi.Schema
	18, // [18:18] is the sub-list for method output_type
	18, // [18:18] is the sub-list for method input_type
	11, // [11:18] is the sub-list for extension type_name
	4,  // [4:11] is the sub-list for extension extendee
	0,  // [0:4] is the sub-list for field type_name
}

func init() { file_gopencloud_gateway_annotations_proto_init() }
func file_gopencloud_gateway_annotations_proto_init() {
	if File_gopencloud_gateway_annotations_proto != nil {
		return
	}
	file_gopencloud_gateway_gateway_proto_init()
	file_gopencloud_gateway_annotations_proto_msgTypes[0].OneofWrappers = []any{
		(*ProtoEndpointBinding_Get)(nil),
		(*ProtoEndpointBinding_Put)(nil),
		(*ProtoEndpointBinding_Post)(nil),
		(*ProtoEndpointBinding_Delete)(nil),
		(*ProtoEndpointBinding_Patch)(nil),
		(*ProtoEndpointBinding_Custom)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_gopencloud_gateway_annotations_proto_rawDesc), len(file_gopencloud_gateway_annotations_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 7,
			NumServices:   0,
		},
		GoTypes:           file_gopencloud_gateway_annotations_proto_goTypes,
		DependencyIndexes: file_gopencloud_gateway_annotations_proto_depIdxs,
		MessageInfos:      file_gopencloud_gateway_annotations_proto_msgTypes,
		ExtensionInfos:    file_gopencloud_gateway_annotations_proto_extTypes,
	}.Build()
	File_gopencloud_gateway_annotations_proto = out.File
	file_gopencloud_gateway_annotations_proto_goTypes = nil
	file_gopencloud_gateway_annotations_proto_depIdxs = nil
}
