// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.9
// 	protoc        (unknown)
// source: gopencloud/gateway/config.proto

package api

import (
	openapi "github.com/gopencloud/grpc-api-gateway/api/openapi"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// OpenAPIServiceSpec defines configuration for generating OpenAPI documentation for gRPC services.
type OpenAPIServiceSpec struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// selector is a dot-separated gRPC service method selector.
	//
	// If the selector begins with '~.', the current proto package will be added to the beginning
	// of the path. For instance: `~.MyService`. Since no proto package can be deduced in the global
	// config file, this alias cannot be used in the global config file.
	//
	// If the selector does not begin with '~.', it will be treated as a fully qualified method name (FQMN).
	Selector string `protobuf:"bytes,1,opt,name=selector,proto3" json:"selector,omitempty"`
	// document can be used to override default values for OpenAPI document files when using the option to generate
	// OpenAPI files per service.
	//
	// Additionally, this can be used to change documentation generation behavior such as default responses regardless
	// of the output generation mode.
	//
	// NOTE: This document will only be used when using output mode of "service" and in all other
	// modes, this object simply gets ignored save for the config field. Since the config field instructs
	// the generation of responses and the document objects for that service only, regardless of the output mode
	// the settings will be honored.
	Document *openapi.Document `protobuf:"bytes,2,opt,name=document,proto3" json:"document,omitempty"`
	// methods maps each method to an operation configuration.
	Methods       map[string]*openapi.Operation `protobuf:"bytes,3,rep,name=methods,proto3" json:"methods,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OpenAPIServiceSpec) Reset() {
	*x = OpenAPIServiceSpec{}
	mi := &file_gopencloud_gateway_config_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OpenAPIServiceSpec) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OpenAPIServiceSpec) ProtoMessage() {}

func (x *OpenAPIServiceSpec) ProtoReflect() protoreflect.Message {
	mi := &file_gopencloud_gateway_config_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OpenAPIServiceSpec.ProtoReflect.Descriptor instead.
func (*OpenAPIServiceSpec) Descriptor() ([]byte, []int) {
	return file_gopencloud_gateway_config_proto_rawDescGZIP(), []int{0}
}

func (x *OpenAPIServiceSpec) GetSelector() string {
	if x != nil {
		return x.Selector
	}
	return ""
}

func (x *OpenAPIServiceSpec) GetDocument() *openapi.Document {
	if x != nil {
		return x.Document
	}
	return nil
}

func (x *OpenAPIServiceSpec) GetMethods() map[string]*openapi.Operation {
	if x != nil {
		return x.Methods
	}
	return nil
}

// OpenAPIMessageSpec defines configuration for generating OpenAPI documentation for protobuf messages.
type OpenAPIMessageSpec struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// selector is a dot-separated protobuf message selector.
	//
	// If the selector begins with a '.', it will be treated as an absolute path.
	// If it begins with '~.', the current proto package will be added to the beginning
	// of the path. For instance: `~.MyMessage`. Since no proto package can be deduced in the global
	// config file, this alias cannot be used in the global config file.
	// If the path does not begin with a '.' or '~.', it will be treated as a relative path and a search
	// from the current proto package will be performed in order to find the message.
	Selector string `protobuf:"bytes,1,opt,name=selector,proto3" json:"selector,omitempty"`
	// schema controls the OpenAPI v3.1 schema generation for this proto message.
	Schema *openapi.Schema `protobuf:"bytes,2,opt,name=schema,proto3" json:"schema,omitempty"`
	// fields allows controlling the OpenAPI v3.1 generation for individual fields in this proto message.
	Fields        map[string]*openapi.Schema `protobuf:"bytes,3,rep,name=fields,proto3" json:"fields,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OpenAPIMessageSpec) Reset() {
	*x = OpenAPIMessageSpec{}
	mi := &file_gopencloud_gateway_config_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OpenAPIMessageSpec) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OpenAPIMessageSpec) ProtoMessage() {}

func (x *OpenAPIMessageSpec) ProtoReflect() protoreflect.Message {
	mi := &file_gopencloud_gateway_config_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OpenAPIMessageSpec.ProtoReflect.Descriptor instead.
func (*OpenAPIMessageSpec) Descriptor() ([]byte, []int) {
	return file_gopencloud_gateway_config_proto_rawDescGZIP(), []int{1}
}

func (x *OpenAPIMessageSpec) GetSelector() string {
	if x != nil {
		return x.Selector
	}
	return ""
}

func (x *OpenAPIMessageSpec) GetSchema() *openapi.Schema {
	if x != nil {
		return x.Schema
	}
	return nil
}

func (x *OpenAPIMessageSpec) GetFields() map[string]*openapi.Schema {
	if x != nil {
		return x.Fields
	}
	return nil
}

// OpenAPIEnumSpec defines configuration for generating OpenAPI documentation for protobuf enums.
type OpenAPIEnumSpec struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// selector is a dot-separated protobuf enum selector.
	//
	// If the selector begins with a '.', it will be treated as an absolute path.
	// If it begins with '~.', the current proto package will be added to the beginning
	// of the path. For instance: `~.MyEnum`. Since no proto package can be deduced in the global
	// config file, this alias cannot be used in the global config file.
	// If the path does not begin with a '.' or '~.', it will be treated as a relative path and a search
	// from the current proto package will be performed in order to find the enum.
	Selector string `protobuf:"bytes,1,opt,name=selector,proto3" json:"selector,omitempty"`
	// schema controls the OpenAPI v3.1 schema generation for this proto enum.
	Schema        *openapi.Schema `protobuf:"bytes,2,opt,name=schema,proto3" json:"schema,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OpenAPIEnumSpec) Reset() {
	*x = OpenAPIEnumSpec{}
	mi := &file_gopencloud_gateway_config_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OpenAPIEnumSpec) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OpenAPIEnumSpec) ProtoMessage() {}

func (x *OpenAPIEnumSpec) ProtoReflect() protoreflect.Message {
	mi := &file_gopencloud_gateway_config_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OpenAPIEnumSpec.ProtoReflect.Descriptor instead.
func (*OpenAPIEnumSpec) Descriptor() ([]byte, []int) {
	return file_gopencloud_gateway_config_proto_rawDescGZIP(), []int{2}
}

func (x *OpenAPIEnumSpec) GetSelector() string {
	if x != nil {
		return x.Selector
	}
	return ""
}

func (x *OpenAPIEnumSpec) GetSchema() *openapi.Schema {
	if x != nil {
		return x.Schema
	}
	return nil
}

// OpenAPISpec defines the overall OpenAPI documentation configuration.
type OpenAPISpec struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Document is the OpenAPI v3.1 document configuration which controls how the OpenAPI documentation is generated.
	//
	// This document can be defined to define a base config for all documents (if in the global config) or the document
	// for the current output target. For instance, when using output mode of "service", each service defined in the
	// associated proto file inherits this base document and can additionally specify more defaults for its own OpenAPI
	// document. When defining this in the global config and for specific proto files, the configs get merged together
	// but the priority is given to the proto document.
	Document *openapi.Document `protobuf:"bytes,1,opt,name=document,proto3" json:"document,omitempty"`
	// services is used to configure OpenAPI v3.1 output for gRPC services.
	Services []*OpenAPIServiceSpec `protobuf:"bytes,2,rep,name=services,proto3" json:"services,omitempty"`
	// messages is used to configure OpenAPI v3.1 output for protobuf messages.
	Messages []*OpenAPIMessageSpec `protobuf:"bytes,3,rep,name=messages,proto3" json:"messages,omitempty"`
	// enums is used to configure OpenAPI v3.1 output for protobuf enums.
	Enums         []*OpenAPIEnumSpec `protobuf:"bytes,4,rep,name=enums,proto3" json:"enums,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OpenAPISpec) Reset() {
	*x = OpenAPISpec{}
	mi := &file_gopencloud_gateway_config_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OpenAPISpec) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OpenAPISpec) ProtoMessage() {}

func (x *OpenAPISpec) ProtoReflect() protoreflect.Message {
	mi := &file_gopencloud_gateway_config_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OpenAPISpec.ProtoReflect.Descriptor instead.
func (*OpenAPISpec) Descriptor() ([]byte, []int) {
	return file_gopencloud_gateway_config_proto_rawDescGZIP(), []int{3}
}

func (x *OpenAPISpec) GetDocument() *openapi.Document {
	if x != nil {
		return x.Document
	}
	return nil
}

func (x *OpenAPISpec) GetServices() []*OpenAPIServiceSpec {
	if x != nil {
		return x.Services
	}
	return nil
}

func (x *OpenAPISpec) GetMessages() []*OpenAPIMessageSpec {
	if x != nil {
		return x.Messages
	}
	return nil
}

func (x *OpenAPISpec) GetEnums() []*OpenAPIEnumSpec {
	if x != nil {
		return x.Enums
	}
	return nil
}

// Config is the content of a configuration file.
type Config struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// gateway holds gateway configs.
	Gateway *GatewaySpec `protobuf:"bytes,1,opt,name=gateway,proto3" json:"gateway,omitempty"`
	// openapi holds OpenAPI v3.1 configs.
	Openapi       *OpenAPISpec `protobuf:"bytes,2,opt,name=openapi,proto3" json:"openapi,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Config) Reset() {
	*x = Config{}
	mi := &file_gopencloud_gateway_config_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Config) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Config) ProtoMessage() {}

func (x *Config) ProtoReflect() protoreflect.Message {
	mi := &file_gopencloud_gateway_config_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Config.ProtoReflect.Descriptor instead.
func (*Config) Descriptor() ([]byte, []int) {
	return file_gopencloud_gateway_config_proto_rawDescGZIP(), []int{4}
}

func (x *Config) GetGateway() *GatewaySpec {
	if x != nil {
		return x.Gateway
	}
	return nil
}

func (x *Config) GetOpenapi() *OpenAPISpec {
	if x != nil {
		return x.Openapi
	}
	return nil
}

var File_gopencloud_gateway_config_proto protoreflect.FileDescriptor

const file_gopencloud_gateway_config_proto_rawDesc = "" +
	"\n" +
	"\x1fgopencloud/gateway/config.proto\x12\x12gopencloud.gateway\x1a gopencloud/gateway/gateway.proto\x1a(gopencloud/gateway/openapi/openapi.proto\"\xa4\x02\n" +
	"\x12OpenAPIServiceSpec\x12\x1a\n" +
	"\bselector\x18\x01 \x01(\tR\bselector\x12@\n" +
	"\bdocument\x18\x02 \x01(\v2$.gopencloud.gateway.openapi.DocumentR\bdocument\x12M\n" +
	"\amethods\x18\x03 \x03(\v23.gopencloud.gateway.OpenAPIServiceSpec.MethodsEntryR\amethods\x1aa\n" +
	"\fMethodsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12;\n" +
	"\x05value\x18\x02 \x01(\v2%.gopencloud.gateway.openapi.OperationR\x05value:\x028\x01\"\x97\x02\n" +
	"\x12OpenAPIMessageSpec\x12\x1a\n" +
	"\bselector\x18\x01 \x01(\tR\bselector\x12:\n" +
	"\x06schema\x18\x02 \x01(\v2\".gopencloud.gateway.openapi.SchemaR\x06schema\x12J\n" +
	"\x06fields\x18\x03 \x03(\v22.gopencloud.gateway.OpenAPIMessageSpec.FieldsEntryR\x06fields\x1a]\n" +
	"\vFieldsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x128\n" +
	"\x05value\x18\x02 \x01(\v2\".gopencloud.gateway.openapi.SchemaR\x05value:\x028\x01\"i\n" +
	"\x0fOpenAPIEnumSpec\x12\x1a\n" +
	"\bselector\x18\x01 \x01(\tR\bselector\x12:\n" +
	"\x06schema\x18\x02 \x01(\v2\".gopencloud.gateway.openapi.SchemaR\x06schema\"\x92\x02\n" +
	"\vOpenAPISpec\x12@\n" +
	"\bdocument\x18\x01 \x01(\v2$.gopencloud.gateway.openapi.DocumentR\bdocument\x12B\n" +
	"\bservices\x18\x02 \x03(\v2&.gopencloud.gateway.OpenAPIServiceSpecR\bservices\x12B\n" +
	"\bmessages\x18\x03 \x03(\v2&.gopencloud.gateway.OpenAPIMessageSpecR\bmessages\x129\n" +
	"\x05enums\x18\x04 \x03(\v2#.gopencloud.gateway.OpenAPIEnumSpecR\x05enums\"~\n" +
	"\x06Config\x129\n" +
	"\agateway\x18\x01 \x01(\v2\x1f.gopencloud.gateway.GatewaySpecR\agateway\x129\n" +
	"\aopenapi\x18\x02 \x01(\v2\x1f.gopencloud.gateway.OpenAPISpecR\aopenapiB,Z*github.com/gopencloud/grpc-api-gateway/apib\x06proto3"

var (
	file_gopencloud_gateway_config_proto_rawDescOnce sync.Once
	file_gopencloud_gateway_config_proto_rawDescData []byte
)

func file_gopencloud_gateway_config_proto_rawDescGZIP() []byte {
	file_gopencloud_gateway_config_proto_rawDescOnce.Do(func() {
		file_gopencloud_gateway_config_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_gopencloud_gateway_config_proto_rawDesc), len(file_gopencloud_gateway_config_proto_rawDesc)))
	})
	return file_gopencloud_gateway_config_proto_rawDescData
}

var file_gopencloud_gateway_config_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_gopencloud_gateway_config_proto_goTypes = []any{
	(*OpenAPIServiceSpec)(nil), // 0: gopencloud.gateway.OpenAPIServiceSpec
	(*OpenAPIMessageSpec)(nil), // 1: gopencloud.gateway.OpenAPIMessageSpec
	(*OpenAPIEnumSpec)(nil),    // 2: gopencloud.gateway.OpenAPIEnumSpec
	(*OpenAPISpec)(nil),        // 3: gopencloud.gateway.OpenAPISpec
	(*Config)(nil),             // 4: gopencloud.gateway.Config
	nil,                        // 5: gopencloud.gateway.OpenAPIServiceSpec.MethodsEntry
	nil,                        // 6: gopencloud.gateway.OpenAPIMessageSpec.FieldsEntry
	(*openapi.Document)(nil),   // 7: gopencloud.gateway.openapi.Document
	(*openapi.Schema)(nil),     // 8: gopencloud.gateway.openapi.Schema
	(*GatewaySpec)(nil),        // 9: gopencloud.gateway.GatewaySpec
	(*openapi.Operation)(nil),  // 10: gopencloud.gateway.openapi.Operation
}
var file_gopencloud_gateway_config_proto_depIdxs = []int32{
	7,  // 0: gopencloud.gateway.OpenAPIServiceSpec.document:type_name -> gopencloud.gateway.openapi.Document
	5,  // 1: gopencloud.gateway.OpenAPIServiceSpec.methods:type_name -> gopencloud.gateway.OpenAPIServiceSpec.MethodsEntry
	8,  // 2: gopencloud.gateway.OpenAPIMessageSpec.schema:type_name -> gopencloud.gateway.openapi.Schema
	6,  // 3: gopencloud.gateway.OpenAPIMessageSpec.fields:type_name -> gopencloud.gateway.OpenAPIMessageSpec.FieldsEntry
	8,  // 4: gopencloud.gateway.OpenAPIEnumSpec.schema:type_name -> gopencloud.gateway.openapi.Schema
	7,  // 5: gopencloud.gateway.OpenAPISpec.document:type_name -> gopencloud.gateway.openapi.Document
	0,  // 6: gopencloud.gateway.OpenAPISpec.services:type_name -> gopencloud.gateway.OpenAPIServiceSpec
	1,  // 7: gopencloud.gateway.OpenAPISpec.messages:type_name -> gopencloud.gateway.OpenAPIMessageSpec
	2,  // 8: gopencloud.gateway.OpenAPISpec.enums:type_name -> gopencloud.gateway.OpenAPIEnumSpec
	9,  // 9: gopencloud.gateway.Config.gateway:type_name -> gopencloud.gateway.GatewaySpec
	3,  // 10: gopencloud.gateway.Config.openapi:type_name -> gopencloud.gateway.OpenAPISpec
	10, // 11: gopencloud.gateway.OpenAPIServiceSpec.MethodsEntry.value:type_name -> gopencloud.gateway.openapi.Operation
	8,  // 12: gopencloud.gateway.OpenAPIMessageSpec.FieldsEntry.value:type_name -> gopencloud.gateway.openapi.Schema
	13, // [13:13] is the sub-list for method output_type
	13, // [13:13] is the sub-list for method input_type
	13, // [13:13] is the sub-list for extension type_name
	13, // [13:13] is the sub-list for extension extendee
	0,  // [0:13] is the sub-list for field type_name
}

func init() { file_gopencloud_gateway_config_proto_init() }
func file_gopencloud_gateway_config_proto_init() {
	if File_gopencloud_gateway_config_proto != nil {
		return
	}
	file_gopencloud_gateway_gateway_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_gopencloud_gateway_config_proto_rawDesc), len(file_gopencloud_gateway_config_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_gopencloud_gateway_config_proto_goTypes,
		DependencyIndexes: file_gopencloud_gateway_config_proto_depIdxs,
		MessageInfos:      file_gopencloud_gateway_config_proto_msgTypes,
	}.Build()
	File_gopencloud_gateway_config_proto = out.File
	file_gopencloud_gateway_config_proto_goTypes = nil
	file_gopencloud_gateway_config_proto_depIdxs = nil
}
