// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.9
// 	protoc        (unknown)
// source: gopencloud/gateway/gateway.proto

package api

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// GatewaySpec holds gRPC gateway configurations.
type GatewaySpec struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// endpoints hold a series of endpoint binding specs.
	Endpoints     []*EndpointBinding `protobuf:"bytes,1,rep,name=endpoints" json:"endpoints,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GatewaySpec) Reset() {
	*x = GatewaySpec{}
	mi := &file_gopencloud_gateway_gateway_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GatewaySpec) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GatewaySpec) ProtoMessage() {}

func (x *GatewaySpec) ProtoReflect() protoreflect.Message {
	mi := &file_gopencloud_gateway_gateway_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GatewaySpec.ProtoReflect.Descriptor instead.
func (*GatewaySpec) Descriptor() ([]byte, []int) {
	return file_gopencloud_gateway_gateway_proto_rawDescGZIP(), []int{0}
}

func (x *GatewaySpec) GetEndpoints() []*EndpointBinding {
	if x != nil {
		return x.Endpoints
	}
	return nil
}

// EndpointBinding represents an HTTP endpoint(s) to gRPC method binding.
type EndpointBinding struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// selector is a dot-separated gRPC service method selector.
	//
	// If the selector begins with `~.`, the current proto package will be added
	// to the beginning of the path. For instance: `~.MyService`. Since no proto
	// package can be deduced in the global config file, this alias cannot be used
	// in the global config file.
	//
	// If the selector does not begin with `~.`, it will be treated as a fully
	// qualified method name (FQMN).
	//
	// NOTE: In proto annotations, this field gets automatically assigned, thus it
	// is only applicable in configuration files.
	Selector *string `protobuf:"bytes,1,opt,name=selector" json:"selector,omitempty"`
	// pattern specifies the HTTP method for this endpoint binding.
	//
	// Types that are valid to be assigned to Pattern:
	//
	//	*EndpointBinding_Get
	//	*EndpointBinding_Put
	//	*EndpointBinding_Post
	//	*EndpointBinding_Delete
	//	*EndpointBinding_Patch
	//	*EndpointBinding_Custom
	Pattern isEndpointBinding_Pattern `protobuf_oneof:"pattern"`
	// body is a request message field selector that will be read via HTTP body.
	//
	// `*` indicates that the entire request message gets decoded from the body.
	// An empty string (default value) indicates that no part of the request gets
	// decoded from the body.
	//
	// NOTE: Not all methods support HTTP body.
	Body *string `protobuf:"bytes,8,opt,name=body" json:"body,omitempty"`
	// response_body is a response message field selector that will be written to
	// HTTP response.
	//
	// `*` or an empty string indicates that the entire response message gets
	// encoded.
	ResponseBody *string `protobuf:"bytes,9,opt,name=response_body,json=responseBody" json:"response_body,omitempty"`
	// query_params are explicit query parameter bindings that can be used to
	// rename or ignore query parameters.
	QueryParams []*QueryParameterBinding `protobuf:"bytes,10,rep,name=query_params,json=queryParams" json:"query_params,omitempty"`
	// additional_bindings holds additional bindings for the same gRPC service
	// method.
	AdditionalBindings []*AdditionalEndpointBinding `protobuf:"bytes,11,rep,name=additional_bindings,json=additionalBindings" json:"additional_bindings,omitempty"`
	// disable_query_param_discovery can be used to avoid auto binding query
	// parameters.
	//
	// Default: `false`
	DisableQueryParamDiscovery *bool `protobuf:"varint,12,opt,name=disable_query_param_discovery,json=disableQueryParamDiscovery" json:"disable_query_param_discovery,omitempty"`
	// stream holds configurations for streaming methods.
	Stream *StreamConfig `protobuf:"bytes,13,opt,name=stream" json:"stream,omitempty"`
	// aliases are additional routes for this endpoint binding.
	//
	// This field translates to additional_bindings, inheriting all values from
	// endpoint binding. Consider this a syntax sugar for additional_bindings. If
	// additional binding with same route and method exists, alias will not work.
	Aliases       []string `protobuf:"bytes,14,rep,name=aliases" json:"aliases,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EndpointBinding) Reset() {
	*x = EndpointBinding{}
	mi := &file_gopencloud_gateway_gateway_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EndpointBinding) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EndpointBinding) ProtoMessage() {}

func (x *EndpointBinding) ProtoReflect() protoreflect.Message {
	mi := &file_gopencloud_gateway_gateway_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EndpointBinding.ProtoReflect.Descriptor instead.
func (*EndpointBinding) Descriptor() ([]byte, []int) {
	return file_gopencloud_gateway_gateway_proto_rawDescGZIP(), []int{1}
}

func (x *EndpointBinding) GetSelector() string {
	if x != nil && x.Selector != nil {
		return *x.Selector
	}
	return ""
}

func (x *EndpointBinding) GetPattern() isEndpointBinding_Pattern {
	if x != nil {
		return x.Pattern
	}
	return nil
}

func (x *EndpointBinding) GetGet() string {
	if x != nil {
		if x, ok := x.Pattern.(*EndpointBinding_Get); ok {
			return x.Get
		}
	}
	return ""
}

func (x *EndpointBinding) GetPut() string {
	if x != nil {
		if x, ok := x.Pattern.(*EndpointBinding_Put); ok {
			return x.Put
		}
	}
	return ""
}

func (x *EndpointBinding) GetPost() string {
	if x != nil {
		if x, ok := x.Pattern.(*EndpointBinding_Post); ok {
			return x.Post
		}
	}
	return ""
}

func (x *EndpointBinding) GetDelete() string {
	if x != nil {
		if x, ok := x.Pattern.(*EndpointBinding_Delete); ok {
			return x.Delete
		}
	}
	return ""
}

func (x *EndpointBinding) GetPatch() string {
	if x != nil {
		if x, ok := x.Pattern.(*EndpointBinding_Patch); ok {
			return x.Patch
		}
	}
	return ""
}

func (x *EndpointBinding) GetCustom() *CustomPattern {
	if x != nil {
		if x, ok := x.Pattern.(*EndpointBinding_Custom); ok {
			return x.Custom
		}
	}
	return nil
}

func (x *EndpointBinding) GetBody() string {
	if x != nil && x.Body != nil {
		return *x.Body
	}
	return ""
}

func (x *EndpointBinding) GetResponseBody() string {
	if x != nil && x.ResponseBody != nil {
		return *x.ResponseBody
	}
	return ""
}

func (x *EndpointBinding) GetQueryParams() []*QueryParameterBinding {
	if x != nil {
		return x.QueryParams
	}
	return nil
}

func (x *EndpointBinding) GetAdditionalBindings() []*AdditionalEndpointBinding {
	if x != nil {
		return x.AdditionalBindings
	}
	return nil
}

func (x *EndpointBinding) GetDisableQueryParamDiscovery() bool {
	if x != nil && x.DisableQueryParamDiscovery != nil {
		return *x.DisableQueryParamDiscovery
	}
	return false
}

func (x *EndpointBinding) GetStream() *StreamConfig {
	if x != nil {
		return x.Stream
	}
	return nil
}

func (x *EndpointBinding) GetAliases() []string {
	if x != nil {
		return x.Aliases
	}
	return nil
}

type isEndpointBinding_Pattern interface {
	isEndpointBinding_Pattern()
}

type EndpointBinding_Get struct {
	// get defines route for a GET HTTP endpoint.
	Get string `protobuf:"bytes,2,opt,name=get,oneof"`
}

type EndpointBinding_Put struct {
	// put defines route for a PUT HTTP endpoint.
	Put string `protobuf:"bytes,3,opt,name=put,oneof"`
}

type EndpointBinding_Post struct {
	// post defines route for a POST HTTP endpoint.
	Post string `protobuf:"bytes,4,opt,name=post,oneof"`
}

type EndpointBinding_Delete struct {
	// delete defines route for a DELETE HTTP endpoint.
	Delete string `protobuf:"bytes,5,opt,name=delete,oneof"`
}

type EndpointBinding_Patch struct {
	// patch defines route for a PATCH HTTP endpoint.
	Patch string `protobuf:"bytes,6,opt,name=patch,oneof"`
}

type EndpointBinding_Custom struct {
	// custom can be used for custom HTTP methods.
	//
	// Not all HTTP methods are supported in OpenAPI specification and will not
	// be included in the generated OpenAPI document.
	Custom *CustomPattern `protobuf:"bytes,7,opt,name=custom,oneof"`
}

func (*EndpointBinding_Get) isEndpointBinding_Pattern() {}

func (*EndpointBinding_Put) isEndpointBinding_Pattern() {}

func (*EndpointBinding_Post) isEndpointBinding_Pattern() {}

func (*EndpointBinding_Delete) isEndpointBinding_Pattern() {}

func (*EndpointBinding_Patch) isEndpointBinding_Pattern() {}

func (*EndpointBinding_Custom) isEndpointBinding_Pattern() {}

// AdditionalEndpointBinding is an additional gRPC method - HTTP endpoint
// binding specification.
type AdditionalEndpointBinding struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// pattern specifies the HTTP method for this additional endpoint binding.
	//
	// Types that are valid to be assigned to Pattern:
	//
	//	*AdditionalEndpointBinding_Get
	//	*AdditionalEndpointBinding_Put
	//	*AdditionalEndpointBinding_Post
	//	*AdditionalEndpointBinding_Delete
	//	*AdditionalEndpointBinding_Patch
	//	*AdditionalEndpointBinding_Custom
	Pattern isAdditionalEndpointBinding_Pattern `protobuf_oneof:"pattern"`
	// body is a request message field selector that will be read via HTTP body.
	//
	// '*' indicates that the entire request message gets decoded from the body.
	// An empty string indicates that no part of the request gets decoded from the
	// body.
	//
	// NOTE: Not all methods support HTTP body.
	Body *string `protobuf:"bytes,8,opt,name=body" json:"body,omitempty"`
	// response_body is a response message field selector that will be written to
	// HTTP response.
	//
	// '*' or an empty string indicates that the entire response message gets
	// encoded.
	ResponseBody *string `protobuf:"bytes,9,opt,name=response_body,json=responseBody" json:"response_body,omitempty"`
	// query_params are explicit query parameter bindings that can be used to
	// rename or ignore query parameters.
	QueryParams []*QueryParameterBinding `protobuf:"bytes,10,rep,name=query_params,json=queryParams" json:"query_params,omitempty"`
	// disable_query_param_discovery can be used to avoid auto binding query
	// parameters.
	DisableQueryParamDiscovery *bool `protobuf:"varint,11,opt,name=disable_query_param_discovery,json=disableQueryParamDiscovery" json:"disable_query_param_discovery,omitempty"`
	// stream holds configurations for streaming methods.
	Stream        *StreamConfig `protobuf:"bytes,12,opt,name=stream" json:"stream,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AdditionalEndpointBinding) Reset() {
	*x = AdditionalEndpointBinding{}
	mi := &file_gopencloud_gateway_gateway_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AdditionalEndpointBinding) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AdditionalEndpointBinding) ProtoMessage() {}

func (x *AdditionalEndpointBinding) ProtoReflect() protoreflect.Message {
	mi := &file_gopencloud_gateway_gateway_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AdditionalEndpointBinding.ProtoReflect.Descriptor instead.
func (*AdditionalEndpointBinding) Descriptor() ([]byte, []int) {
	return file_gopencloud_gateway_gateway_proto_rawDescGZIP(), []int{2}
}

func (x *AdditionalEndpointBinding) GetPattern() isAdditionalEndpointBinding_Pattern {
	if x != nil {
		return x.Pattern
	}
	return nil
}

func (x *AdditionalEndpointBinding) GetGet() string {
	if x != nil {
		if x, ok := x.Pattern.(*AdditionalEndpointBinding_Get); ok {
			return x.Get
		}
	}
	return ""
}

func (x *AdditionalEndpointBinding) GetPut() string {
	if x != nil {
		if x, ok := x.Pattern.(*AdditionalEndpointBinding_Put); ok {
			return x.Put
		}
	}
	return ""
}

func (x *AdditionalEndpointBinding) GetPost() string {
	if x != nil {
		if x, ok := x.Pattern.(*AdditionalEndpointBinding_Post); ok {
			return x.Post
		}
	}
	return ""
}

func (x *AdditionalEndpointBinding) GetDelete() string {
	if x != nil {
		if x, ok := x.Pattern.(*AdditionalEndpointBinding_Delete); ok {
			return x.Delete
		}
	}
	return ""
}

func (x *AdditionalEndpointBinding) GetPatch() string {
	if x != nil {
		if x, ok := x.Pattern.(*AdditionalEndpointBinding_Patch); ok {
			return x.Patch
		}
	}
	return ""
}

func (x *AdditionalEndpointBinding) GetCustom() *CustomPattern {
	if x != nil {
		if x, ok := x.Pattern.(*AdditionalEndpointBinding_Custom); ok {
			return x.Custom
		}
	}
	return nil
}

func (x *AdditionalEndpointBinding) GetBody() string {
	if x != nil && x.Body != nil {
		return *x.Body
	}
	return ""
}

func (x *AdditionalEndpointBinding) GetResponseBody() string {
	if x != nil && x.ResponseBody != nil {
		return *x.ResponseBody
	}
	return ""
}

func (x *AdditionalEndpointBinding) GetQueryParams() []*QueryParameterBinding {
	if x != nil {
		return x.QueryParams
	}
	return nil
}

func (x *AdditionalEndpointBinding) GetDisableQueryParamDiscovery() bool {
	if x != nil && x.DisableQueryParamDiscovery != nil {
		return *x.DisableQueryParamDiscovery
	}
	return false
}

func (x *AdditionalEndpointBinding) GetStream() *StreamConfig {
	if x != nil {
		return x.Stream
	}
	return nil
}

type isAdditionalEndpointBinding_Pattern interface {
	isAdditionalEndpointBinding_Pattern()
}

type AdditionalEndpointBinding_Get struct {
	Get string `protobuf:"bytes,2,opt,name=get,oneof"`
}

type AdditionalEndpointBinding_Put struct {
	Put string `protobuf:"bytes,3,opt,name=put,oneof"`
}

type AdditionalEndpointBinding_Post struct {
	Post string `protobuf:"bytes,4,opt,name=post,oneof"`
}

type AdditionalEndpointBinding_Delete struct {
	Delete string `protobuf:"bytes,5,opt,name=delete,oneof"`
}

type AdditionalEndpointBinding_Patch struct {
	Patch string `protobuf:"bytes,6,opt,name=patch,oneof"`
}

type AdditionalEndpointBinding_Custom struct {
	// custom can be used for custom HTTP methods.
	//
	// Not all HTTP methods are supported in OpenAPI specification, however and
	// will not be included in the generated OpenAPI document.
	Custom *CustomPattern `protobuf:"bytes,7,opt,name=custom,oneof"`
}

func (*AdditionalEndpointBinding_Get) isAdditionalEndpointBinding_Pattern() {}

func (*AdditionalEndpointBinding_Put) isAdditionalEndpointBinding_Pattern() {}

func (*AdditionalEndpointBinding_Post) isAdditionalEndpointBinding_Pattern() {}

func (*AdditionalEndpointBinding_Delete) isAdditionalEndpointBinding_Pattern() {}

func (*AdditionalEndpointBinding_Patch) isAdditionalEndpointBinding_Pattern() {}

func (*AdditionalEndpointBinding_Custom) isAdditionalEndpointBinding_Pattern() {}

// CustomPattern describes an HTTP pattern and custom method.
type CustomPattern struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// method is the custom HTTP method.
	Method *string `protobuf:"bytes,1,opt,name=method" json:"method,omitempty"`
	// path is the HTTP path pattern.
	Path          *string `protobuf:"bytes,2,opt,name=path" json:"path,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CustomPattern) Reset() {
	*x = CustomPattern{}
	mi := &file_gopencloud_gateway_gateway_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CustomPattern) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CustomPattern) ProtoMessage() {}

func (x *CustomPattern) ProtoReflect() protoreflect.Message {
	mi := &file_gopencloud_gateway_gateway_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CustomPattern.ProtoReflect.Descriptor instead.
func (*CustomPattern) Descriptor() ([]byte, []int) {
	return file_gopencloud_gateway_gateway_proto_rawDescGZIP(), []int{3}
}

func (x *CustomPattern) GetMethod() string {
	if x != nil && x.Method != nil {
		return *x.Method
	}
	return ""
}

func (x *CustomPattern) GetPath() string {
	if x != nil && x.Path != nil {
		return *x.Path
	}
	return ""
}

// QueryParameterBinding describes a query parameter to request message binding.
type QueryParameterBinding struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// selector is a dot-separated path to the request message's field.
	Selector *string `protobuf:"bytes,1,opt,name=selector" json:"selector,omitempty"`
	// name is the name of the HTTP query parameter that will be used.
	Name *string `protobuf:"bytes,2,opt,name=name" json:"name,omitempty"`
	// ignore avoids reading this query parameter altogether (default: false).
	Ignore        *bool `protobuf:"varint,3,opt,name=ignore" json:"ignore,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *QueryParameterBinding) Reset() {
	*x = QueryParameterBinding{}
	mi := &file_gopencloud_gateway_gateway_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QueryParameterBinding) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QueryParameterBinding) ProtoMessage() {}

func (x *QueryParameterBinding) ProtoReflect() protoreflect.Message {
	mi := &file_gopencloud_gateway_gateway_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QueryParameterBinding.ProtoReflect.Descriptor instead.
func (*QueryParameterBinding) Descriptor() ([]byte, []int) {
	return file_gopencloud_gateway_gateway_proto_rawDescGZIP(), []int{4}
}

func (x *QueryParameterBinding) GetSelector() string {
	if x != nil && x.Selector != nil {
		return *x.Selector
	}
	return ""
}

func (x *QueryParameterBinding) GetName() string {
	if x != nil && x.Name != nil {
		return *x.Name
	}
	return ""
}

func (x *QueryParameterBinding) GetIgnore() bool {
	if x != nil && x.Ignore != nil {
		return *x.Ignore
	}
	return false
}

// StreamConfig sets the behavior of the HTTP server for gRPC streaming methods.
type StreamConfig struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// disable_websockets indicates whether or not websockets are allowed for this
	// method. The client must still ask for a connection upgrade.
	DisableWebsockets *bool `protobuf:"varint,1,opt,name=disable_websockets,json=disableWebsockets" json:"disable_websockets,omitempty"`
	// disable_sse indicates whether or not server-sent events are allowed.
	//
	// see:
	// https://developer.mozilla.org/en-US/docs/Web/API/Server-sent_events/Using_server-sent_events
	//
	// SSE is only used when Accept-Type from the request includes MIME type
	// text/event-stream.
	DisableSse *bool `protobuf:"varint,2,opt,name=disable_sse,json=disableSse" json:"disable_sse,omitempty"`
	// disable_chunked indicates whether or not chunked transfer encoding is
	// allowed.
	//
	// NOTE: Chunked transfer encoding is disabled in HTTP/2 so this option will
	// only be available if the request is HTTP/1.
	DisableChunkedTransfer *bool `protobuf:"varint,3,opt,name=disable_chunked_transfer,json=disableChunkedTransfer" json:"disable_chunked_transfer,omitempty"`
	unknownFields          protoimpl.UnknownFields
	sizeCache              protoimpl.SizeCache
}

func (x *StreamConfig) Reset() {
	*x = StreamConfig{}
	mi := &file_gopencloud_gateway_gateway_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StreamConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StreamConfig) ProtoMessage() {}

func (x *StreamConfig) ProtoReflect() protoreflect.Message {
	mi := &file_gopencloud_gateway_gateway_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StreamConfig.ProtoReflect.Descriptor instead.
func (*StreamConfig) Descriptor() ([]byte, []int) {
	return file_gopencloud_gateway_gateway_proto_rawDescGZIP(), []int{5}
}

func (x *StreamConfig) GetDisableWebsockets() bool {
	if x != nil && x.DisableWebsockets != nil {
		return *x.DisableWebsockets
	}
	return false
}

func (x *StreamConfig) GetDisableSse() bool {
	if x != nil && x.DisableSse != nil {
		return *x.DisableSse
	}
	return false
}

func (x *StreamConfig) GetDisableChunkedTransfer() bool {
	if x != nil && x.DisableChunkedTransfer != nil {
		return *x.DisableChunkedTransfer
	}
	return false
}

var File_gopencloud_gateway_gateway_proto protoreflect.FileDescriptor

const file_gopencloud_gateway_gateway_proto_rawDesc = "" +
	"\n" +
	" gopencloud/gateway/gateway.proto\x12\x12gopencloud.gateway\"P\n" +
	"\vGatewaySpec\x12A\n" +
	"\tendpoints\x18\x01 \x03(\v2#.gopencloud.gateway.EndpointBindingR\tendpoints\"\xe3\x04\n" +
	"\x0fEndpointBinding\x12\x1a\n" +
	"\bselector\x18\x01 \x01(\tR\bselector\x12\x12\n" +
	"\x03get\x18\x02 \x01(\tH\x00R\x03get\x12\x12\n" +
	"\x03put\x18\x03 \x01(\tH\x00R\x03put\x12\x14\n" +
	"\x04post\x18\x04 \x01(\tH\x00R\x04post\x12\x18\n" +
	"\x06delete\x18\x05 \x01(\tH\x00R\x06delete\x12\x16\n" +
	"\x05patch\x18\x06 \x01(\tH\x00R\x05patch\x12;\n" +
	"\x06custom\x18\a \x01(\v2!.gopencloud.gateway.CustomPatternH\x00R\x06custom\x12\x12\n" +
	"\x04body\x18\b \x01(\tR\x04body\x12#\n" +
	"\rresponse_body\x18\t \x01(\tR\fresponseBody\x12L\n" +
	"\fquery_params\x18\n" +
	" \x03(\v2).gopencloud.gateway.QueryParameterBindingR\vqueryParams\x12^\n" +
	"\x13additional_bindings\x18\v \x03(\v2-.gopencloud.gateway.AdditionalEndpointBindingR\x12additionalBindings\x12A\n" +
	"\x1ddisable_query_param_discovery\x18\f \x01(\bR\x1adisableQueryParamDiscovery\x128\n" +
	"\x06stream\x18\r \x01(\v2 .gopencloud.gateway.StreamConfigR\x06stream\x12\x18\n" +
	"\aaliases\x18\x0e \x03(\tR\aaliasesB\t\n" +
	"\apattern\"\xd7\x03\n" +
	"\x19AdditionalEndpointBinding\x12\x12\n" +
	"\x03get\x18\x02 \x01(\tH\x00R\x03get\x12\x12\n" +
	"\x03put\x18\x03 \x01(\tH\x00R\x03put\x12\x14\n" +
	"\x04post\x18\x04 \x01(\tH\x00R\x04post\x12\x18\n" +
	"\x06delete\x18\x05 \x01(\tH\x00R\x06delete\x12\x16\n" +
	"\x05patch\x18\x06 \x01(\tH\x00R\x05patch\x12;\n" +
	"\x06custom\x18\a \x01(\v2!.gopencloud.gateway.CustomPatternH\x00R\x06custom\x12\x12\n" +
	"\x04body\x18\b \x01(\tR\x04body\x12#\n" +
	"\rresponse_body\x18\t \x01(\tR\fresponseBody\x12L\n" +
	"\fquery_params\x18\n" +
	" \x03(\v2).gopencloud.gateway.QueryParameterBindingR\vqueryParams\x12A\n" +
	"\x1ddisable_query_param_discovery\x18\v \x01(\bR\x1adisableQueryParamDiscovery\x128\n" +
	"\x06stream\x18\f \x01(\v2 .gopencloud.gateway.StreamConfigR\x06streamB\t\n" +
	"\apattern\";\n" +
	"\rCustomPattern\x12\x16\n" +
	"\x06method\x18\x01 \x01(\tR\x06method\x12\x12\n" +
	"\x04path\x18\x02 \x01(\tR\x04path\"_\n" +
	"\x15QueryParameterBinding\x12\x1a\n" +
	"\bselector\x18\x01 \x01(\tR\bselector\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x16\n" +
	"\x06ignore\x18\x03 \x01(\bR\x06ignore\"\x98\x01\n" +
	"\fStreamConfig\x12-\n" +
	"\x12disable_websockets\x18\x01 \x01(\bR\x11disableWebsockets\x12\x1f\n" +
	"\vdisable_sse\x18\x02 \x01(\bR\n" +
	"disableSse\x128\n" +
	"\x18disable_chunked_transfer\x18\x03 \x01(\bR\x16disableChunkedTransferB,Z*github.com/gopencloud/grpc-api-gateway/apib\beditionsp\xe8\a"

var (
	file_gopencloud_gateway_gateway_proto_rawDescOnce sync.Once
	file_gopencloud_gateway_gateway_proto_rawDescData []byte
)

func file_gopencloud_gateway_gateway_proto_rawDescGZIP() []byte {
	file_gopencloud_gateway_gateway_proto_rawDescOnce.Do(func() {
		file_gopencloud_gateway_gateway_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_gopencloud_gateway_gateway_proto_rawDesc), len(file_gopencloud_gateway_gateway_proto_rawDesc)))
	})
	return file_gopencloud_gateway_gateway_proto_rawDescData
}

var file_gopencloud_gateway_gateway_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_gopencloud_gateway_gateway_proto_goTypes = []any{
	(*GatewaySpec)(nil),               // 0: gopencloud.gateway.GatewaySpec
	(*EndpointBinding)(nil),           // 1: gopencloud.gateway.EndpointBinding
	(*AdditionalEndpointBinding)(nil), // 2: gopencloud.gateway.AdditionalEndpointBinding
	(*CustomPattern)(nil),             // 3: gopencloud.gateway.CustomPattern
	(*QueryParameterBinding)(nil),     // 4: gopencloud.gateway.QueryParameterBinding
	(*StreamConfig)(nil),              // 5: gopencloud.gateway.StreamConfig
}
var file_gopencloud_gateway_gateway_proto_depIdxs = []int32{
	1, // 0: gopencloud.gateway.GatewaySpec.endpoints:type_name -> gopencloud.gateway.EndpointBinding
	3, // 1: gopencloud.gateway.EndpointBinding.custom:type_name -> gopencloud.gateway.CustomPattern
	4, // 2: gopencloud.gateway.EndpointBinding.query_params:type_name -> gopencloud.gateway.QueryParameterBinding
	2, // 3: gopencloud.gateway.EndpointBinding.additional_bindings:type_name -> gopencloud.gateway.AdditionalEndpointBinding
	5, // 4: gopencloud.gateway.EndpointBinding.stream:type_name -> gopencloud.gateway.StreamConfig
	3, // 5: gopencloud.gateway.AdditionalEndpointBinding.custom:type_name -> gopencloud.gateway.CustomPattern
	4, // 6: gopencloud.gateway.AdditionalEndpointBinding.query_params:type_name -> gopencloud.gateway.QueryParameterBinding
	5, // 7: gopencloud.gateway.AdditionalEndpointBinding.stream:type_name -> gopencloud.gateway.StreamConfig
	8, // [8:8] is the sub-list for method output_type
	8, // [8:8] is the sub-list for method input_type
	8, // [8:8] is the sub-list for extension type_name
	8, // [8:8] is the sub-list for extension extendee
	0, // [0:8] is the sub-list for field type_name
}

func init() { file_gopencloud_gateway_gateway_proto_init() }
func file_gopencloud_gateway_gateway_proto_init() {
	if File_gopencloud_gateway_gateway_proto != nil {
		return
	}
	file_gopencloud_gateway_gateway_proto_msgTypes[1].OneofWrappers = []any{
		(*EndpointBinding_Get)(nil),
		(*EndpointBinding_Put)(nil),
		(*EndpointBinding_Post)(nil),
		(*EndpointBinding_Delete)(nil),
		(*EndpointBinding_Patch)(nil),
		(*EndpointBinding_Custom)(nil),
	}
	file_gopencloud_gateway_gateway_proto_msgTypes[2].OneofWrappers = []any{
		(*AdditionalEndpointBinding_Get)(nil),
		(*AdditionalEndpointBinding_Put)(nil),
		(*AdditionalEndpointBinding_Post)(nil),
		(*AdditionalEndpointBinding_Delete)(nil),
		(*AdditionalEndpointBinding_Patch)(nil),
		(*AdditionalEndpointBinding_Custom)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_gopencloud_gateway_gateway_proto_rawDesc), len(file_gopencloud_gateway_gateway_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_gopencloud_gateway_gateway_proto_goTypes,
		DependencyIndexes: file_gopencloud_gateway_gateway_proto_depIdxs,
		MessageInfos:      file_gopencloud_gateway_gateway_proto_msgTypes,
	}.Build()
	File_gopencloud_gateway_gateway_proto = out.File
	file_gopencloud_gateway_gateway_proto_goTypes = nil
	file_gopencloud_gateway_gateway_proto_depIdxs = nil
}
