# yaml-language-server: $schema=https://raw.githubusercontent.com/SchemaStore/schemastore/refs/heads/master/src/schemas/json/github-workflow.json
name: Publish docs via GitHub Pages
on:
  push:
    tags:
      - "*"
    branches:
      - main

jobs:
  build:
    name: Deploy docs
    runs-on: ubuntu-latest
    permissions:
      actions: write
      pages: write
    steps:
      - name: Checkout main
        uses: actions/checkout@v4

      - name: Deploy docs
        uses: mhausenblas/mkdocs-deploy-gh-pages@master
        env:
          CONFIG_FILE: mkdocs.yml
